using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Eleooo.DAL
{
	/// <summary>
	/// Strongly-typed collection for the SysMessage class.
	/// </summary>
    [Serializable]
	public partial class SysMessageCollection : ActiveList<SysMessage, SysMessageCollection>
	{	   
		public SysMessageCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>SysMessageCollection</returns>
		public SysMessageCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                SysMessage o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the Sys_Message table.
	/// </summary>
	[Serializable]
	public partial class SysMessage : ActiveRecord<SysMessage>, IActiveRecord
	{
		#region .ctors and Default Settings
		static SysMessage( )
        {
            BaseSchema = DB.GetSchema("Sys_Message");
        }
		public SysMessage()
		{
		  //InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public SysMessage(bool useDatabaseDefaults)
		{ 
            if(BaseSchema == null)
                BaseSchema = DB.GetSchema("Sys_Message");
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public SysMessage(object keyID)
		{ 
            if(BaseSchema == null) 
                BaseSchema = DB.GetSchema("Sys_Message");
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public SysMessage(string columnName, object columnValue)
		{ 
            if(BaseSchema == null) 
                BaseSchema = DB.GetSchema("Sys_Message");
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
                {
                    BaseSchema = DB.GetSchema("Sys_Message");
                }
				return BaseSchema;
			}
		}
		
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
		public int Id 
		{
			get { return GetColumnValue<int>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("MessageType")]
		[Bindable(true)]
		public int MessageType 
		{
			get { return GetColumnValue<int>(Columns.MessageType); }
			set { SetColumnValue(Columns.MessageType, value); }
		}
		  
		[XmlAttribute("MessageSellerID")]
		[Bindable(true)]
		public int MessageSellerID 
		{
			get { return GetColumnValue<int>(Columns.MessageSellerID); }
			set { SetColumnValue(Columns.MessageSellerID, value); }
		}
		  
		[XmlAttribute("MessageSubject")]
		[Bindable(true)]
		public string MessageSubject 
		{
			get { return GetColumnValue<string>(Columns.MessageSubject); }
			set { SetColumnValue(Columns.MessageSubject, value); }
		}
		  
		[XmlAttribute("MessageReply")]
		[Bindable(true)]
		public string MessageReply 
		{
			get { return GetColumnValue<string>(Columns.MessageReply); }
			set { SetColumnValue(Columns.MessageReply, value); }
		}
		  
		[XmlAttribute("MessageSalerID")]
		[Bindable(true)]
		public int MessageSalerID 
		{
			get { return GetColumnValue<int>(Columns.MessageSalerID); }
			set { SetColumnValue(Columns.MessageSalerID, value); }
		}
		  
		[XmlAttribute("MessageDateSubject")]
		[Bindable(true)]
		public DateTime MessageDateSubject 
		{
			get { return GetColumnValue<DateTime>(Columns.MessageDateSubject); }
			set { SetColumnValue(Columns.MessageDateSubject, value); }
		}
		  
		[XmlAttribute("MessageDateReply")]
		[Bindable(true)]
		public decimal MessageDateReply 
		{
			get { return GetColumnValue<decimal>(Columns.MessageDateReply); }
			set { SetColumnValue(Columns.MessageDateReply, value); }
		}
		  
		[XmlAttribute("CreatedBy")]
		[Bindable(true)]
		public int? CreatedBy 
		{
			get { return GetColumnValue<int?>(Columns.CreatedBy); }
			set { SetColumnValue(Columns.CreatedBy, value); }
		}
		  
		[XmlAttribute("CreatedOn")]
		[Bindable(true)]
		public DateTime? CreatedOn 
		{
			get { return GetColumnValue<DateTime?>(Columns.CreatedOn); }
			set { SetColumnValue(Columns.CreatedOn, value); }
		}
		  
		[XmlAttribute("ModifiedBy")]
		[Bindable(true)]
		public int? ModifiedBy 
		{
			get { return GetColumnValue<int?>(Columns.ModifiedBy); }
			set { SetColumnValue(Columns.ModifiedBy, value); }
		}
		  
		[XmlAttribute("ModifiedOn")]
		[Bindable(true)]
		public DateTime? ModifiedOn 
		{
			get { return GetColumnValue<DateTime?>(Columns.ModifiedOn); }
			set { SetColumnValue(Columns.ModifiedOn, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(int varMessageType,int varMessageSellerID,string varMessageSubject,string varMessageReply,int varMessageSalerID,DateTime varMessageDateSubject,decimal varMessageDateReply,int? varCreatedBy,DateTime? varCreatedOn,int? varModifiedBy,DateTime? varModifiedOn)
		{
			SysMessage item = new SysMessage();
			
			item.MessageType = varMessageType;
			
			item.MessageSellerID = varMessageSellerID;
			
			item.MessageSubject = varMessageSubject;
			
			item.MessageReply = varMessageReply;
			
			item.MessageSalerID = varMessageSalerID;
			
			item.MessageDateSubject = varMessageDateSubject;
			
			item.MessageDateReply = varMessageDateReply;
			
			item.CreatedBy = varCreatedBy;
			
			item.CreatedOn = varCreatedOn;
			
			item.ModifiedBy = varModifiedBy;
			
			item.ModifiedOn = varModifiedOn;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varId,int varMessageType,int varMessageSellerID,string varMessageSubject,string varMessageReply,int varMessageSalerID,DateTime varMessageDateSubject,decimal varMessageDateReply,int? varCreatedBy,DateTime? varCreatedOn,int? varModifiedBy,DateTime? varModifiedOn)
		{
			SysMessage item = new SysMessage();
			
				item.Id = varId;
			
				item.MessageType = varMessageType;
			
				item.MessageSellerID = varMessageSellerID;
			
				item.MessageSubject = varMessageSubject;
			
				item.MessageReply = varMessageReply;
			
				item.MessageSalerID = varMessageSalerID;
			
				item.MessageDateSubject = varMessageDateSubject;
			
				item.MessageDateReply = varMessageDateReply;
			
				item.CreatedBy = varCreatedBy;
			
				item.CreatedOn = varCreatedOn;
			
				item.ModifiedBy = varModifiedBy;
			
				item.ModifiedOn = varModifiedOn;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn MessageTypeColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn MessageSellerIDColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn MessageSubjectColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn MessageReplyColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn MessageSalerIDColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        public static TableSchema.TableColumn MessageDateSubjectColumn
        {
            get { return Schema.Columns[6]; }
        }
        
        
        
        public static TableSchema.TableColumn MessageDateReplyColumn
        {
            get { return Schema.Columns[7]; }
        }
        
        
        
        public static TableSchema.TableColumn CreatedByColumn
        {
            get { return Schema.Columns[8]; }
        }
        
        
        
        public static TableSchema.TableColumn CreatedOnColumn
        {
            get { return Schema.Columns[9]; }
        }
        
        
        
        public static TableSchema.TableColumn ModifiedByColumn
        {
            get { return Schema.Columns[10]; }
        }
        
        
        
        public static TableSchema.TableColumn ModifiedOnColumn
        {
            get { return Schema.Columns[11]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"ID";
			 public static string MessageType = @"MessageType";
			 public static string MessageSellerID = @"MessageSellerID";
			 public static string MessageSubject = @"MessageSubject";
			 public static string MessageReply = @"MessageReply";
			 public static string MessageSalerID = @"MessageSalerID";
			 public static string MessageDateSubject = @"MessageDateSubject";
			 public static string MessageDateReply = @"MessageDateReply";
			 public static string CreatedBy = @"CreatedBy";
			 public static string CreatedOn = @"CreatedOn";
			 public static string ModifiedBy = @"ModifiedBy";
			 public static string ModifiedOn = @"ModifiedOn";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
