using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Eleooo.DAL
{
	/// <summary>
	/// Strongly-typed collection for the SysMsnLog class.
	/// </summary>
    [Serializable]
	public partial class SysMsnLogCollection : ActiveList<SysMsnLog, SysMsnLogCollection>
	{	   
		public SysMsnLogCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>SysMsnLogCollection</returns>
		public SysMsnLogCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                SysMsnLog o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the Sys_Msn_Log table.
	/// </summary>
	[Serializable]
	public partial class SysMsnLog : ActiveRecord<SysMsnLog>, IActiveRecord
	{
		#region .ctors and Default Settings
		static SysMsnLog( )
        {
            BaseSchema = DB.GetSchema("Sys_Msn_Log");
        }
		public SysMsnLog()
		{
		  //InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public SysMsnLog(bool useDatabaseDefaults)
		{ 
            if(BaseSchema == null)
                BaseSchema = DB.GetSchema("Sys_Msn_Log");
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public SysMsnLog(object keyID)
		{ 
            if(BaseSchema == null) 
                BaseSchema = DB.GetSchema("Sys_Msn_Log");
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public SysMsnLog(string columnName, object columnValue)
		{ 
            if(BaseSchema == null) 
                BaseSchema = DB.GetSchema("Sys_Msn_Log");
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
                {
                    BaseSchema = DB.GetSchema("Sys_Msn_Log");
                }
				return BaseSchema;
			}
		}
		
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
		public int Id 
		{
			get { return GetColumnValue<int>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("PhoneNumber")]
		[Bindable(true)]
		public string PhoneNumber 
		{
			get { return GetColumnValue<string>(Columns.PhoneNumber); }
			set { SetColumnValue(Columns.PhoneNumber, value); }
		}
		  
		[XmlAttribute("MsnContent")]
		[Bindable(true)]
		public string MsnContent 
		{
			get { return GetColumnValue<string>(Columns.MsnContent); }
			set { SetColumnValue(Columns.MsnContent, value); }
		}
		  
		[XmlAttribute("MsnDate")]
		[Bindable(true)]
		public DateTime? MsnDate 
		{
			get { return GetColumnValue<DateTime?>(Columns.MsnDate); }
			set { SetColumnValue(Columns.MsnDate, value); }
		}
		  
		[XmlAttribute("MsnCode")]
		[Bindable(true)]
		public string MsnCode 
		{
			get { return GetColumnValue<string>(Columns.MsnCode); }
			set { SetColumnValue(Columns.MsnCode, value); }
		}
		  
		[XmlAttribute("IsChecked")]
		[Bindable(true)]
		public bool? IsChecked 
		{
			get { return GetColumnValue<bool?>(Columns.IsChecked); }
			set { SetColumnValue(Columns.IsChecked, value); }
		}
		  
		[XmlAttribute("OrderId")]
		[Bindable(true)]
		public int? OrderId 
		{
			get { return GetColumnValue<int?>(Columns.OrderId); }
			set { SetColumnValue(Columns.OrderId, value); }
		}
		  
		[XmlAttribute("Status")]
		[Bindable(true)]
		public string Status 
		{
			get { return GetColumnValue<string>(Columns.Status); }
			set { SetColumnValue(Columns.Status, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varPhoneNumber,string varMsnContent,DateTime? varMsnDate,string varMsnCode,bool? varIsChecked,int? varOrderId,string varStatus)
		{
			SysMsnLog item = new SysMsnLog();
			
			item.PhoneNumber = varPhoneNumber;
			
			item.MsnContent = varMsnContent;
			
			item.MsnDate = varMsnDate;
			
			item.MsnCode = varMsnCode;
			
			item.IsChecked = varIsChecked;
			
			item.OrderId = varOrderId;
			
			item.Status = varStatus;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varId,string varPhoneNumber,string varMsnContent,DateTime? varMsnDate,string varMsnCode,bool? varIsChecked,int? varOrderId,string varStatus)
		{
			SysMsnLog item = new SysMsnLog();
			
				item.Id = varId;
			
				item.PhoneNumber = varPhoneNumber;
			
				item.MsnContent = varMsnContent;
			
				item.MsnDate = varMsnDate;
			
				item.MsnCode = varMsnCode;
			
				item.IsChecked = varIsChecked;
			
				item.OrderId = varOrderId;
			
				item.Status = varStatus;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn PhoneNumberColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn MsnContentColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn MsnDateColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn MsnCodeColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn IsCheckedColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        public static TableSchema.TableColumn OrderIdColumn
        {
            get { return Schema.Columns[6]; }
        }
        
        
        
        public static TableSchema.TableColumn StatusColumn
        {
            get { return Schema.Columns[7]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"ID";
			 public static string PhoneNumber = @"PhoneNumber";
			 public static string MsnContent = @"MsnContent";
			 public static string MsnDate = @"MsnDate";
			 public static string MsnCode = @"MsnCode";
			 public static string IsChecked = @"IsChecked";
			 public static string OrderId = @"OrderId";
			 public static string Status = @"Status";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
