using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Eleooo.DAL
{
	/// <summary>
	/// Strongly-typed collection for the SysTakeawayMenu class.
	/// </summary>
    [Serializable]
	public partial class SysTakeawayMenuCollection : ActiveList<SysTakeawayMenu, SysTakeawayMenuCollection>
	{	   
		public SysTakeawayMenuCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>SysTakeawayMenuCollection</returns>
		public SysTakeawayMenuCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                SysTakeawayMenu o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the Sys_Takeaway_Menu table.
	/// </summary>
	[Serializable]
	public partial class SysTakeawayMenu : ActiveRecord<SysTakeawayMenu>, IActiveRecord
	{
		#region .ctors and Default Settings
		static SysTakeawayMenu( )
        {
            BaseSchema = DB.GetSchema("Sys_Takeaway_Menu");
        }
		public SysTakeawayMenu()
		{
		  //InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public SysTakeawayMenu(bool useDatabaseDefaults)
		{ 
            if(BaseSchema == null)
                BaseSchema = DB.GetSchema("Sys_Takeaway_Menu");
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public SysTakeawayMenu(object keyID)
		{ 
            if(BaseSchema == null) 
                BaseSchema = DB.GetSchema("Sys_Takeaway_Menu");
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public SysTakeawayMenu(string columnName, object columnValue)
		{ 
            if(BaseSchema == null) 
                BaseSchema = DB.GetSchema("Sys_Takeaway_Menu");
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
                {
                    BaseSchema = DB.GetSchema("Sys_Takeaway_Menu");
                }
				return BaseSchema;
			}
		}
		
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
		public int Id 
		{
			get { return GetColumnValue<int>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("Name")]
		[Bindable(true)]
		public string Name 
		{
			get { return GetColumnValue<string>(Columns.Name); }
			set { SetColumnValue(Columns.Name, value); }
		}
		  
		[XmlAttribute("Price")]
		[Bindable(true)]
		public decimal? Price 
		{
			get { return GetColumnValue<decimal?>(Columns.Price); }
			set { SetColumnValue(Columns.Price, value); }
		}
		  
		[XmlAttribute("DirID")]
		[Bindable(true)]
		public int? DirID 
		{
			get { return GetColumnValue<int?>(Columns.DirID); }
			set { SetColumnValue(Columns.DirID, value); }
		}
		  
		[XmlAttribute("Code")]
		[Bindable(true)]
		public string Code 
		{
			get { return GetColumnValue<string>(Columns.Code); }
			set { SetColumnValue(Columns.Code, value); }
		}
		  
		[XmlAttribute("CompanyID")]
		[Bindable(true)]
		public int? CompanyID 
		{
			get { return GetColumnValue<int?>(Columns.CompanyID); }
			set { SetColumnValue(Columns.CompanyID, value); }
		}
		  
		[XmlAttribute("IsDeleted")]
		[Bindable(true)]
		public bool? IsDeleted 
		{
			get { return GetColumnValue<bool?>(Columns.IsDeleted); }
			set { SetColumnValue(Columns.IsDeleted, value); }
		}
		  
		[XmlAttribute("IsOutOfStock")]
		[Bindable(true)]
		public bool? IsOutOfStock 
		{
			get { return GetColumnValue<bool?>(Columns.IsOutOfStock); }
			set { SetColumnValue(Columns.IsOutOfStock, value); }
		}
		  
		[XmlAttribute("OutOfStockDate")]
		[Bindable(true)]
		public DateTime? OutOfStockDate 
		{
			get { return GetColumnValue<DateTime?>(Columns.OutOfStockDate); }
			set { SetColumnValue(Columns.OutOfStockDate, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varName,decimal? varPrice,int? varDirID,string varCode,int? varCompanyID,bool? varIsDeleted,bool? varIsOutOfStock,DateTime? varOutOfStockDate)
		{
			SysTakeawayMenu item = new SysTakeawayMenu();
			
			item.Name = varName;
			
			item.Price = varPrice;
			
			item.DirID = varDirID;
			
			item.Code = varCode;
			
			item.CompanyID = varCompanyID;
			
			item.IsDeleted = varIsDeleted;
			
			item.IsOutOfStock = varIsOutOfStock;
			
			item.OutOfStockDate = varOutOfStockDate;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varId,string varName,decimal? varPrice,int? varDirID,string varCode,int? varCompanyID,bool? varIsDeleted,bool? varIsOutOfStock,DateTime? varOutOfStockDate)
		{
			SysTakeawayMenu item = new SysTakeawayMenu();
			
				item.Id = varId;
			
				item.Name = varName;
			
				item.Price = varPrice;
			
				item.DirID = varDirID;
			
				item.Code = varCode;
			
				item.CompanyID = varCompanyID;
			
				item.IsDeleted = varIsDeleted;
			
				item.IsOutOfStock = varIsOutOfStock;
			
				item.OutOfStockDate = varOutOfStockDate;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn NameColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn PriceColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn DirIDColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn CodeColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn CompanyIDColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        public static TableSchema.TableColumn IsDeletedColumn
        {
            get { return Schema.Columns[6]; }
        }
        
        
        
        public static TableSchema.TableColumn IsOutOfStockColumn
        {
            get { return Schema.Columns[7]; }
        }
        
        
        
        public static TableSchema.TableColumn OutOfStockDateColumn
        {
            get { return Schema.Columns[8]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"ID";
			 public static string Name = @"Name";
			 public static string Price = @"Price";
			 public static string DirID = @"DirID";
			 public static string Code = @"Code";
			 public static string CompanyID = @"CompanyID";
			 public static string IsDeleted = @"IsDeleted";
			 public static string IsOutOfStock = @"IsOutOfStock";
			 public static string OutOfStockDate = @"OutOfStockDate";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
