using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Eleooo.DAL{
    /// <summary>
    /// Strongly-typed collection for the VFinancePayMemberCash class.
    /// </summary>
    [Serializable]
    public partial class VFinancePayMemberCashCollection : ReadOnlyList<VFinancePayMemberCash, VFinancePayMemberCashCollection>
    {        
        public VFinancePayMemberCashCollection() {}
    }
    /// <summary>
    /// This is  Read-only wrapper class for the v_FinancePay_MemberCash view.
    /// </summary>
    [Serializable]
    public partial class VFinancePayMemberCash : ReadOnlyRecord<VFinancePayMemberCash>, IReadOnlyRecord
    {
    
	    #region Default Settings
	    #endregion
        #region Schema Accessor
	    public static TableSchema.Table Schema
        {
            get
            {
                if (BaseSchema == null)
                {
                    BaseSchema = DB.GetSchema("v_FinancePay_MemberCash");
                }
                return BaseSchema;
            }
        }
    	
        #endregion
        
        #region Query Accessor
	    public static Query CreateQuery()
	    {
		    return new Query(Schema);
	    }
	    #endregion
	    
	    #region .ctors
	    public VFinancePayMemberCash()
	    {
            //SetDefaults();
            //MarkNew(); 
            if(BaseSchema ==null) 
                BaseSchema = DB.GetSchema("v_FinancePay_MemberCash");
        }
        public VFinancePayMemberCash(bool useDatabaseDefaults)
	    { 
            if(BaseSchema == null)
                BaseSchema = DB.GetSchema("v_FinancePay_MemberCash");
		    if(useDatabaseDefaults)
		    {
				ForceDefaults();
			}
			//MarkNew();
	    }
	    
	    public VFinancePayMemberCash(object keyID)
	    { 
            if(BaseSchema == null) 
                BaseSchema = DB.GetSchema("v_FinancePay_MemberCash");
		    LoadByKey(keyID);
	    }
    	 
	    public VFinancePayMemberCash(string columnName, object columnValue)
        { 
            if(BaseSchema == null) 
                BaseSchema = DB.GetSchema("v_FinancePay_MemberCash");
            LoadByParam(columnName,columnValue);
        }
        
	    #endregion
	    
	    #region Props
	    
          
        [XmlAttribute("CashID")]
        [Bindable(true)]
        public int CashID 
	    {
		    get
		    {
			    return GetColumnValue<int>("CashID");
		    }
            set 
		    {
			    SetColumnValue("CashID", value);
            }
        }
	      
        [XmlAttribute("CashDate")]
        [Bindable(true)]
        public DateTime? CashDate 
	    {
		    get
		    {
			    return GetColumnValue<DateTime?>("CashDate");
		    }
            set 
		    {
			    SetColumnValue("CashDate", value);
            }
        }
	      
        [XmlAttribute("CashMemberID")]
        [Bindable(true)]
        public int? CashMemberID 
	    {
		    get
		    {
			    return GetColumnValue<int?>("CashMemberID");
		    }
            set 
		    {
			    SetColumnValue("CashMemberID", value);
            }
        }
	      
        [XmlAttribute("CashCompanyID")]
        [Bindable(true)]
        public int? CashCompanyID 
	    {
		    get
		    {
			    return GetColumnValue<int?>("CashCompanyID");
		    }
            set 
		    {
			    SetColumnValue("CashCompanyID", value);
            }
        }
	      
        [XmlAttribute("CashOrderID")]
        [Bindable(true)]
        public int? CashOrderID 
	    {
		    get
		    {
			    return GetColumnValue<int?>("CashOrderID");
		    }
            set 
		    {
			    SetColumnValue("CashOrderID", value);
            }
        }
	      
        [XmlAttribute("CashSum")]
        [Bindable(true)]
        public decimal? CashSum 
	    {
		    get
		    {
			    return GetColumnValue<decimal?>("CashSum");
		    }
            set 
		    {
			    SetColumnValue("CashSum", value);
            }
        }
	      
        [XmlAttribute("CashRate")]
        [Bindable(true)]
        public decimal? CashRate 
	    {
		    get
		    {
			    return GetColumnValue<decimal?>("CashRate");
		    }
            set 
		    {
			    SetColumnValue("CashRate", value);
            }
        }
	      
        [XmlAttribute("CashPoint")]
        [Bindable(true)]
        public decimal? CashPoint 
	    {
		    get
		    {
			    return GetColumnValue<decimal?>("CashPoint");
		    }
            set 
		    {
			    SetColumnValue("CashPoint", value);
            }
        }
	      
        [XmlAttribute("CashMemo")]
        [Bindable(true)]
        public string CashMemo 
	    {
		    get
		    {
			    return GetColumnValue<string>("CashMemo");
		    }
            set 
		    {
			    SetColumnValue("CashMemo", value);
            }
        }
	      
        [XmlAttribute("CreatedBy")]
        [Bindable(true)]
        public int? CreatedBy 
	    {
		    get
		    {
			    return GetColumnValue<int?>("CreatedBy");
		    }
            set 
		    {
			    SetColumnValue("CreatedBy", value);
            }
        }
	      
        [XmlAttribute("CreatedOn")]
        [Bindable(true)]
        public DateTime? CreatedOn 
	    {
		    get
		    {
			    return GetColumnValue<DateTime?>("CreatedOn");
		    }
            set 
		    {
			    SetColumnValue("CreatedOn", value);
            }
        }
	      
        [XmlAttribute("ModifiedBy")]
        [Bindable(true)]
        public int? ModifiedBy 
	    {
		    get
		    {
			    return GetColumnValue<int?>("ModifiedBy");
		    }
            set 
		    {
			    SetColumnValue("ModifiedBy", value);
            }
        }
	      
        [XmlAttribute("ModifiedOn")]
        [Bindable(true)]
        public DateTime? ModifiedOn 
	    {
		    get
		    {
			    return GetColumnValue<DateTime?>("ModifiedOn");
		    }
            set 
		    {
			    SetColumnValue("ModifiedOn", value);
            }
        }
	    
	    #endregion 
        #region Typed Columns
        
        public static TableSchema.TableColumn
        CashIDColumn { get { return Schema.Columns[0]; } }
        
        public static TableSchema.TableColumn
        CashDateColumn { get { return Schema.Columns[1]; } }
        
        public static TableSchema.TableColumn
        CashMemberIDColumn { get { return Schema.Columns[2]; } }
        
        public static TableSchema.TableColumn
        CashCompanyIDColumn { get { return Schema.Columns[3]; } }
        
        public static TableSchema.TableColumn
        CashOrderIDColumn { get { return Schema.Columns[4]; } }
        
        public static TableSchema.TableColumn
        CashSumColumn { get { return Schema.Columns[5]; } }
        
        public static TableSchema.TableColumn
        CashRateColumn { get { return Schema.Columns[6]; } }
        
        public static TableSchema.TableColumn
        CashPointColumn { get { return Schema.Columns[7]; } }
        
        public static TableSchema.TableColumn
        CashMemoColumn { get { return Schema.Columns[8]; } }
        
        public static TableSchema.TableColumn
        CreatedByColumn { get { return Schema.Columns[9]; } }
        
        public static TableSchema.TableColumn
        CreatedOnColumn { get { return Schema.Columns[10]; } }
        
        public static TableSchema.TableColumn
        ModifiedByColumn { get { return Schema.Columns[11]; } }
        
        public static TableSchema.TableColumn
        ModifiedOnColumn { get { return Schema.Columns[12]; } }
        
        #endregion #region Columns Struct    
	    #region Columns Struct
	    public struct Columns
	    {
		    
		    
            public static string CashID = @"CashID";
            
            public static string CashDate = @"CashDate";
            
            public static string CashMemberID = @"CashMemberID";
            
            public static string CashCompanyID = @"CashCompanyID";
            
            public static string CashOrderID = @"CashOrderID";
            
            public static string CashSum = @"CashSum";
            
            public static string CashRate = @"CashRate";
            
            public static string CashPoint = @"CashPoint";
            
            public static string CashMemo = @"CashMemo";
            
            public static string CreatedBy = @"CreatedBy";
            
            public static string CreatedOn = @"CreatedOn";
            
            public static string ModifiedBy = @"ModifiedBy";
            
            public static string ModifiedOn = @"ModifiedOn";
            
	    }
	    #endregion
	    
	    
	    #region IAbstractRecord Members
        public new CT GetColumnValue<CT>(string columnName) {
            return base.GetColumnValue<CT>(columnName);
        }
        public object GetColumnValue(string columnName) {
            return base.GetColumnValue<object>(columnName);
        }
        #endregion
	    
    }
}
