using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Eleooo.DAL{
    /// <summary>
    /// Strongly-typed collection for the VPaymentRateDate class.
    /// </summary>
    [Serializable]
    public partial class VPaymentRateDateCollection : ReadOnlyList<VPaymentRateDate, VPaymentRateDateCollection>
    {        
        public VPaymentRateDateCollection() {}
    }
    /// <summary>
    /// This is  Read-only wrapper class for the v_PaymentRate_Date view.
    /// </summary>
    [Serializable]
    public partial class VPaymentRateDate : ReadOnlyRecord<VPaymentRateDate>, IReadOnlyRecord
    {
    
	    #region Default Settings
	    #endregion
        #region Schema Accessor
	    public static TableSchema.Table Schema
        {
            get
            {
                if (BaseSchema == null)
                {
                    BaseSchema = DB.GetSchema("v_PaymentRate_Date");
                }
                return BaseSchema;
            }
        }
    	
        #endregion
        
        #region Query Accessor
	    public static Query CreateQuery()
	    {
		    return new Query(Schema);
	    }
	    #endregion
	    
	    #region .ctors
	    public VPaymentRateDate()
	    {
            //SetDefaults();
            //MarkNew(); 
            if(BaseSchema ==null) 
                BaseSchema = DB.GetSchema("v_PaymentRate_Date");
        }
        public VPaymentRateDate(bool useDatabaseDefaults)
	    { 
            if(BaseSchema == null)
                BaseSchema = DB.GetSchema("v_PaymentRate_Date");
		    if(useDatabaseDefaults)
		    {
				ForceDefaults();
			}
			//MarkNew();
	    }
	    
	    public VPaymentRateDate(object keyID)
	    { 
            if(BaseSchema == null) 
                BaseSchema = DB.GetSchema("v_PaymentRate_Date");
		    LoadByKey(keyID);
	    }
    	 
	    public VPaymentRateDate(string columnName, object columnValue)
        { 
            if(BaseSchema == null) 
                BaseSchema = DB.GetSchema("v_PaymentRate_Date");
            LoadByParam(columnName,columnValue);
        }
        
	    #endregion
	    
	    #region Props
	    
          
        [XmlAttribute("PaymentRateDate")]
        [Bindable(true)]
        public DateTime? PaymentRateDate 
	    {
		    get
		    {
			    return GetColumnValue<DateTime?>("PaymentRateDate");
		    }
            set 
		    {
			    SetColumnValue("PaymentRateDate", value);
            }
        }
	      
        [XmlAttribute("PaymentRateCompanyID")]
        [Bindable(true)]
        public int? PaymentRateCompanyID 
	    {
		    get
		    {
			    return GetColumnValue<int?>("PaymentRateCompanyID");
		    }
            set 
		    {
			    SetColumnValue("PaymentRateCompanyID", value);
            }
        }
	    
	    #endregion 
        #region Typed Columns
        
        public static TableSchema.TableColumn
        PaymentRateDateColumn { get { return Schema.Columns[0]; } }
        
        public static TableSchema.TableColumn
        PaymentRateCompanyIDColumn { get { return Schema.Columns[1]; } }
        
        #endregion #region Columns Struct    
	    #region Columns Struct
	    public struct Columns
	    {
		    
		    
            public static string PaymentRateDate = @"PaymentRateDate";
            
            public static string PaymentRateCompanyID = @"PaymentRateCompanyID";
            
	    }
	    #endregion
	    
	    
	    #region IAbstractRecord Members
        public new CT GetColumnValue<CT>(string columnName) {
            return base.GetColumnValue<CT>(columnName);
        }
        public object GetColumnValue(string columnName) {
            return base.GetColumnValue<object>(columnName);
        }
        #endregion
	    
    }
}
