using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Eleooo.DAL{
    /// <summary>
    /// Strongly-typed collection for the VPaymentFirst class.
    /// </summary>
    [Serializable]
    public partial class VPaymentFirstCollection : ReadOnlyList<VPaymentFirst, VPaymentFirstCollection>
    {        
        public VPaymentFirstCollection() {}
    }
    /// <summary>
    /// This is  Read-only wrapper class for the v_Payment_First view.
    /// </summary>
    [Serializable]
    public partial class VPaymentFirst : ReadOnlyRecord<VPaymentFirst>, IReadOnlyRecord
    {
    
	    #region Default Settings
	    #endregion
        #region Schema Accessor
	    public static TableSchema.Table Schema
        {
            get
            {
                if (BaseSchema == null)
                {
                    BaseSchema = DB.GetSchema("v_Payment_First");
                }
                return BaseSchema;
            }
        }
    	
        #endregion
        
        #region Query Accessor
	    public static Query CreateQuery()
	    {
		    return new Query(Schema);
	    }
	    #endregion
	    
	    #region .ctors
	    public VPaymentFirst()
	    {
            //SetDefaults();
            //MarkNew(); 
            if(BaseSchema ==null) 
                BaseSchema = DB.GetSchema("v_Payment_First");
        }
        public VPaymentFirst(bool useDatabaseDefaults)
	    { 
            if(BaseSchema == null)
                BaseSchema = DB.GetSchema("v_Payment_First");
		    if(useDatabaseDefaults)
		    {
				ForceDefaults();
			}
			//MarkNew();
	    }
	    
	    public VPaymentFirst(object keyID)
	    { 
            if(BaseSchema == null) 
                BaseSchema = DB.GetSchema("v_Payment_First");
		    LoadByKey(keyID);
	    }
    	 
	    public VPaymentFirst(string columnName, object columnValue)
        { 
            if(BaseSchema == null) 
                BaseSchema = DB.GetSchema("v_Payment_First");
            LoadByParam(columnName,columnValue);
        }
        
	    #endregion
	    
	    #region Props
	    
          
        [XmlAttribute("PaymentCompanyID")]
        [Bindable(true)]
        public int? PaymentCompanyID 
	    {
		    get
		    {
			    return GetColumnValue<int?>("PaymentCompanyID");
		    }
            set 
		    {
			    SetColumnValue("PaymentCompanyID", value);
            }
        }
	      
        [XmlAttribute("PaymentMemberID")]
        [Bindable(true)]
        public int? PaymentMemberID 
	    {
		    get
		    {
			    return GetColumnValue<int?>("PaymentMemberID");
		    }
            set 
		    {
			    SetColumnValue("PaymentMemberID", value);
            }
        }
	      
        [XmlAttribute("PaymentDate")]
        [Bindable(true)]
        public DateTime? PaymentDate 
	    {
		    get
		    {
			    return GetColumnValue<DateTime?>("PaymentDate");
		    }
            set 
		    {
			    SetColumnValue("PaymentDate", value);
            }
        }
	    
	    #endregion 
        #region Typed Columns
        
        public static TableSchema.TableColumn
        PaymentCompanyIDColumn { get { return Schema.Columns[0]; } }
        
        public static TableSchema.TableColumn
        PaymentMemberIDColumn { get { return Schema.Columns[1]; } }
        
        public static TableSchema.TableColumn
        PaymentDateColumn { get { return Schema.Columns[2]; } }
        
        #endregion #region Columns Struct    
	    #region Columns Struct
	    public struct Columns
	    {
		    
		    
            public static string PaymentCompanyID = @"PaymentCompanyID";
            
            public static string PaymentMemberID = @"PaymentMemberID";
            
            public static string PaymentDate = @"PaymentDate";
            
	    }
	    #endregion
	    
	    
	    #region IAbstractRecord Members
        public new CT GetColumnValue<CT>(string columnName) {
            return base.GetColumnValue<CT>(columnName);
        }
        public object GetColumnValue(string columnName) {
            return base.GetColumnValue<object>(columnName);
        }
        #endregion
	    
    }
}
