using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Eleooo.DAL{
    /// <summary>
    /// Strongly-typed collection for the VSysMemberItemOuter class.
    /// </summary>
    [Serializable]
    public partial class VSysMemberItemOuterCollection : ReadOnlyList<VSysMemberItemOuter, VSysMemberItemOuterCollection>
    {        
        public VSysMemberItemOuterCollection() {}
    }
    /// <summary>
    /// This is  Read-only wrapper class for the v_Sys_Member_Item_Outer view.
    /// </summary>
    [Serializable]
    public partial class VSysMemberItemOuter : ReadOnlyRecord<VSysMemberItemOuter>, IReadOnlyRecord
    {
    
	    #region Default Settings
	    #endregion
        #region Schema Accessor
	    public static TableSchema.Table Schema
        {
            get
            {
                if (BaseSchema == null)
                {
                    BaseSchema = DB.GetSchema("v_Sys_Member_Item_Outer");
                }
                return BaseSchema;
            }
        }
    	
        #endregion
        
        #region Query Accessor
	    public static Query CreateQuery()
	    {
		    return new Query(Schema);
	    }
	    #endregion
	    
	    #region .ctors
	    public VSysMemberItemOuter()
	    {
            //SetDefaults();
            //MarkNew(); 
            if(BaseSchema ==null) 
                BaseSchema = DB.GetSchema("v_Sys_Member_Item_Outer");
        }
        public VSysMemberItemOuter(bool useDatabaseDefaults)
	    { 
            if(BaseSchema == null)
                BaseSchema = DB.GetSchema("v_Sys_Member_Item_Outer");
		    if(useDatabaseDefaults)
		    {
				ForceDefaults();
			}
			//MarkNew();
	    }
	    
	    public VSysMemberItemOuter(object keyID)
	    { 
            if(BaseSchema == null) 
                BaseSchema = DB.GetSchema("v_Sys_Member_Item_Outer");
		    LoadByKey(keyID);
	    }
    	 
	    public VSysMemberItemOuter(string columnName, object columnValue)
        { 
            if(BaseSchema == null) 
                BaseSchema = DB.GetSchema("v_Sys_Member_Item_Outer");
            LoadByParam(columnName,columnValue);
        }
        
	    #endregion
	    
	    #region Props
	    
          
        [XmlAttribute("ItemID")]
        [Bindable(true)]
        public int ItemID 
	    {
		    get
		    {
			    return GetColumnValue<int>("ItemID");
		    }
            set 
		    {
			    SetColumnValue("ItemID", value);
            }
        }
	      
        [XmlAttribute("CompanyItemID")]
        [Bindable(true)]
        public int CompanyItemID 
	    {
		    get
		    {
			    return GetColumnValue<int>("CompanyItemID");
		    }
            set 
		    {
			    SetColumnValue("CompanyItemID", value);
            }
        }
	      
        [XmlAttribute("MemberID")]
        [Bindable(true)]
        public int MemberID 
	    {
		    get
		    {
			    return GetColumnValue<int>("MemberID");
		    }
            set 
		    {
			    SetColumnValue("MemberID", value);
            }
        }
	      
        [XmlAttribute("ItemDate")]
        [Bindable(true)]
        public DateTime ItemDate 
	    {
		    get
		    {
			    return GetColumnValue<DateTime>("ItemDate");
		    }
            set 
		    {
			    SetColumnValue("ItemDate", value);
            }
        }
	      
        [XmlAttribute("ItemStatus")]
        [Bindable(true)]
        public int ItemStatus 
	    {
		    get
		    {
			    return GetColumnValue<int>("ItemStatus");
		    }
            set 
		    {
			    SetColumnValue("ItemStatus", value);
            }
        }
	      
        [XmlAttribute("SetDate")]
        [Bindable(true)]
        public DateTime? SetDate 
	    {
		    get
		    {
			    return GetColumnValue<DateTime?>("SetDate");
		    }
            set 
		    {
			    SetColumnValue("SetDate", value);
            }
        }
	      
        [XmlAttribute("OrderSum")]
        [Bindable(true)]
        public decimal? OrderSum 
	    {
		    get
		    {
			    return GetColumnValue<decimal?>("OrderSum");
		    }
            set 
		    {
			    SetColumnValue("OrderSum", value);
            }
        }
	      
        [XmlAttribute("CompanyID")]
        [Bindable(true)]
        public int? CompanyID 
	    {
		    get
		    {
			    return GetColumnValue<int?>("CompanyID");
		    }
            set 
		    {
			    SetColumnValue("CompanyID", value);
            }
        }
	      
        [XmlAttribute("ItemPoint")]
        [Bindable(true)]
        public decimal? ItemPoint 
	    {
		    get
		    {
			    return GetColumnValue<decimal?>("ItemPoint");
		    }
            set 
		    {
			    SetColumnValue("ItemPoint", value);
            }
        }
	      
        [XmlAttribute("PaymentID")]
        [Bindable(true)]
        public int? PaymentID 
	    {
		    get
		    {
			    return GetColumnValue<int?>("PaymentID");
		    }
            set 
		    {
			    SetColumnValue("PaymentID", value);
            }
        }
	      
        [XmlAttribute("IsCanModifiedDate")]
        [Bindable(true)]
        public bool? IsCanModifiedDate 
	    {
		    get
		    {
			    return GetColumnValue<bool?>("IsCanModifiedDate");
		    }
            set 
		    {
			    SetColumnValue("IsCanModifiedDate", value);
            }
        }
	      
        [XmlAttribute("OrderDate")]
        [Bindable(true)]
        public DateTime? OrderDate 
	    {
		    get
		    {
			    return GetColumnValue<DateTime?>("OrderDate");
		    }
            set 
		    {
			    SetColumnValue("OrderDate", value);
            }
        }
	    
	    #endregion 
        #region Typed Columns
        
        public static TableSchema.TableColumn
        ItemIDColumn { get { return Schema.Columns[0]; } }
        
        public static TableSchema.TableColumn
        CompanyItemIDColumn { get { return Schema.Columns[1]; } }
        
        public static TableSchema.TableColumn
        MemberIDColumn { get { return Schema.Columns[2]; } }
        
        public static TableSchema.TableColumn
        ItemDateColumn { get { return Schema.Columns[3]; } }
        
        public static TableSchema.TableColumn
        ItemStatusColumn { get { return Schema.Columns[4]; } }
        
        public static TableSchema.TableColumn
        SetDateColumn { get { return Schema.Columns[5]; } }
        
        public static TableSchema.TableColumn
        OrderSumColumn { get { return Schema.Columns[6]; } }
        
        public static TableSchema.TableColumn
        CompanyIDColumn { get { return Schema.Columns[7]; } }
        
        public static TableSchema.TableColumn
        ItemPointColumn { get { return Schema.Columns[8]; } }
        
        public static TableSchema.TableColumn
        PaymentIDColumn { get { return Schema.Columns[9]; } }
        
        public static TableSchema.TableColumn
        IsCanModifiedDateColumn { get { return Schema.Columns[10]; } }
        
        public static TableSchema.TableColumn
        OrderDateColumn { get { return Schema.Columns[11]; } }
        
        #endregion #region Columns Struct    
	    #region Columns Struct
	    public struct Columns
	    {
		    
		    
            public static string ItemID = @"ItemID";
            
            public static string CompanyItemID = @"CompanyItemID";
            
            public static string MemberID = @"MemberID";
            
            public static string ItemDate = @"ItemDate";
            
            public static string ItemStatus = @"ItemStatus";
            
            public static string SetDate = @"SetDate";
            
            public static string OrderSum = @"OrderSum";
            
            public static string CompanyID = @"CompanyID";
            
            public static string ItemPoint = @"ItemPoint";
            
            public static string PaymentID = @"PaymentID";
            
            public static string IsCanModifiedDate = @"IsCanModifiedDate";
            
            public static string OrderDate = @"OrderDate";
            
	    }
	    #endregion
	    
	    
	    #region IAbstractRecord Members
        public new CT GetColumnValue<CT>(string columnName) {
            return base.GetColumnValue<CT>(columnName);
        }
        public object GetColumnValue(string columnName) {
            return base.GetColumnValue<object>(columnName);
        }
        #endregion
	    
    }
}
