using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Eleooo.DAL{
    /// <summary>
    /// Strongly-typed collection for the VSysCompanyAdsMaxPoint class.
    /// </summary>
    [Serializable]
    public partial class VSysCompanyAdsMaxPointCollection : ReadOnlyList<VSysCompanyAdsMaxPoint, VSysCompanyAdsMaxPointCollection>
    {        
        public VSysCompanyAdsMaxPointCollection() {}
    }
    /// <summary>
    /// This is  Read-only wrapper class for the v_Sys_Company_Ads_Max_Point view.
    /// </summary>
    [Serializable]
    public partial class VSysCompanyAdsMaxPoint : ReadOnlyRecord<VSysCompanyAdsMaxPoint>, IReadOnlyRecord
    {
    
	    #region Default Settings
	    #endregion
        #region Schema Accessor
	    public static TableSchema.Table Schema
        {
            get
            {
                if (BaseSchema == null)
                {
                    BaseSchema = DB.GetSchema("v_Sys_Company_Ads_Max_Point");
                }
                return BaseSchema;
            }
        }
    	
        #endregion
        
        #region Query Accessor
	    public static Query CreateQuery()
	    {
		    return new Query(Schema);
	    }
	    #endregion
	    
	    #region .ctors
	    public VSysCompanyAdsMaxPoint()
	    {
            //SetDefaults();
            //MarkNew(); 
            if(BaseSchema ==null) 
                BaseSchema = DB.GetSchema("v_Sys_Company_Ads_Max_Point");
        }
        public VSysCompanyAdsMaxPoint(bool useDatabaseDefaults)
	    { 
            if(BaseSchema == null)
                BaseSchema = DB.GetSchema("v_Sys_Company_Ads_Max_Point");
		    if(useDatabaseDefaults)
		    {
				ForceDefaults();
			}
			//MarkNew();
	    }
	    
	    public VSysCompanyAdsMaxPoint(object keyID)
	    { 
            if(BaseSchema == null) 
                BaseSchema = DB.GetSchema("v_Sys_Company_Ads_Max_Point");
		    LoadByKey(keyID);
	    }
    	 
	    public VSysCompanyAdsMaxPoint(string columnName, object columnValue)
        { 
            if(BaseSchema == null) 
                BaseSchema = DB.GetSchema("v_Sys_Company_Ads_Max_Point");
            LoadByParam(columnName,columnValue);
        }
        
	    #endregion
	    
	    #region Props
	    
          
        [XmlAttribute("Id")]
        [Bindable(true)]
        public int Id 
	    {
		    get
		    {
			    return GetColumnValue<int>("ID");
		    }
            set 
		    {
			    SetColumnValue("ID", value);
            }
        }
	      
        [XmlAttribute("AdsID")]
        [Bindable(true)]
        public int? AdsID 
	    {
		    get
		    {
			    return GetColumnValue<int?>("AdsID");
		    }
            set 
		    {
			    SetColumnValue("AdsID", value);
            }
        }
	      
        [XmlAttribute("OrderSumLimit")]
        [Bindable(true)]
        public decimal? OrderSumLimit 
	    {
		    get
		    {
			    return GetColumnValue<decimal?>("OrderSumLimit");
		    }
            set 
		    {
			    SetColumnValue("OrderSumLimit", value);
            }
        }
	      
        [XmlAttribute("AdsPoint")]
        [Bindable(true)]
        public int? AdsPoint 
	    {
		    get
		    {
			    return GetColumnValue<int?>("AdsPoint");
		    }
            set 
		    {
			    SetColumnValue("AdsPoint", value);
            }
        }
	    
	    #endregion 
        #region Typed Columns
        
        public static TableSchema.TableColumn
        IdColumn { get { return Schema.Columns[0]; } }
        
        public static TableSchema.TableColumn
        AdsIDColumn { get { return Schema.Columns[1]; } }
        
        public static TableSchema.TableColumn
        OrderSumLimitColumn { get { return Schema.Columns[2]; } }
        
        public static TableSchema.TableColumn
        AdsPointColumn { get { return Schema.Columns[3]; } }
        
        #endregion #region Columns Struct    
	    #region Columns Struct
	    public struct Columns
	    {
		    
		    
            public static string Id = @"ID";
            
            public static string AdsID = @"AdsID";
            
            public static string OrderSumLimit = @"OrderSumLimit";
            
            public static string AdsPoint = @"AdsPoint";
            
	    }
	    #endregion
	    
	    
	    #region IAbstractRecord Members
        public new CT GetColumnValue<CT>(string columnName) {
            return base.GetColumnValue<CT>(columnName);
        }
        public object GetColumnValue(string columnName) {
            return base.GetColumnValue<object>(columnName);
        }
        #endregion
	    
    }
}
