using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Eleooo.DAL{
    /// <summary>
    /// Strongly-typed collection for the VSysMemberCashMove class.
    /// </summary>
    [Serializable]
    public partial class VSysMemberCashMoveCollection : ReadOnlyList<VSysMemberCashMove, VSysMemberCashMoveCollection>
    {        
        public VSysMemberCashMoveCollection() {}
    }
    /// <summary>
    /// This is  Read-only wrapper class for the v_SysMemberCashMove view.
    /// </summary>
    [Serializable]
    public partial class VSysMemberCashMove : ReadOnlyRecord<VSysMemberCashMove>, IReadOnlyRecord
    {
    
	    #region Default Settings
	    #endregion
        #region Schema Accessor
	    public static TableSchema.Table Schema
        {
            get
            {
                if (BaseSchema == null)
                {
                    BaseSchema = DB.GetSchema("v_SysMemberCashMove");
                }
                return BaseSchema;
            }
        }
    	
        #endregion
        
        #region Query Accessor
	    public static Query CreateQuery()
	    {
		    return new Query(Schema);
	    }
	    #endregion
	    
	    #region .ctors
	    public VSysMemberCashMove()
	    {
            //SetDefaults();
            //MarkNew(); 
            if(BaseSchema ==null) 
                BaseSchema = DB.GetSchema("v_SysMemberCashMove");
        }
        public VSysMemberCashMove(bool useDatabaseDefaults)
	    { 
            if(BaseSchema == null)
                BaseSchema = DB.GetSchema("v_SysMemberCashMove");
		    if(useDatabaseDefaults)
		    {
				ForceDefaults();
			}
			//MarkNew();
	    }
	    
	    public VSysMemberCashMove(object keyID)
	    { 
            if(BaseSchema == null) 
                BaseSchema = DB.GetSchema("v_SysMemberCashMove");
		    LoadByKey(keyID);
	    }
    	 
	    public VSysMemberCashMove(string columnName, object columnValue)
        { 
            if(BaseSchema == null) 
                BaseSchema = DB.GetSchema("v_SysMemberCashMove");
            LoadByParam(columnName,columnValue);
        }
        
	    #endregion
	    
	    #region Props
	    
          
        [XmlAttribute("MoveID")]
        [Bindable(true)]
        public int MoveID 
	    {
		    get
		    {
			    return GetColumnValue<int>("MoveID");
		    }
            set 
		    {
			    SetColumnValue("MoveID", value);
            }
        }
	      
        [XmlAttribute("MoverDate")]
        [Bindable(true)]
        public DateTime? MoverDate 
	    {
		    get
		    {
			    return GetColumnValue<DateTime?>("MoverDate");
		    }
            set 
		    {
			    SetColumnValue("MoverDate", value);
            }
        }
	      
        [XmlAttribute("MoverMemberIDOld")]
        [Bindable(true)]
        public int? MoverMemberIDOld 
	    {
		    get
		    {
			    return GetColumnValue<int?>("MoverMemberIDOld");
		    }
            set 
		    {
			    SetColumnValue("MoverMemberIDOld", value);
            }
        }
	      
        [XmlAttribute("MoverMemberIDNew")]
        [Bindable(true)]
        public int? MoverMemberIDNew 
	    {
		    get
		    {
			    return GetColumnValue<int?>("MoverMemberIDNew");
		    }
            set 
		    {
			    SetColumnValue("MoverMemberIDNew", value);
            }
        }
	      
        [XmlAttribute("MoverMemberIDPoint")]
        [Bindable(true)]
        public int? MoverMemberIDPoint 
	    {
		    get
		    {
			    return GetColumnValue<int?>("MoverMemberIDPoint");
		    }
            set 
		    {
			    SetColumnValue("MoverMemberIDPoint", value);
            }
        }
	      
        [XmlAttribute("CreatedBy")]
        [Bindable(true)]
        public int? CreatedBy 
	    {
		    get
		    {
			    return GetColumnValue<int?>("CreatedBy");
		    }
            set 
		    {
			    SetColumnValue("CreatedBy", value);
            }
        }
	      
        [XmlAttribute("CreatedOn")]
        [Bindable(true)]
        public DateTime? CreatedOn 
	    {
		    get
		    {
			    return GetColumnValue<DateTime?>("CreatedOn");
		    }
            set 
		    {
			    SetColumnValue("CreatedOn", value);
            }
        }
	      
        [XmlAttribute("ModifiedBy")]
        [Bindable(true)]
        public int? ModifiedBy 
	    {
		    get
		    {
			    return GetColumnValue<int?>("ModifiedBy");
		    }
            set 
		    {
			    SetColumnValue("ModifiedBy", value);
            }
        }
	      
        [XmlAttribute("ModifiedOn")]
        [Bindable(true)]
        public DateTime? ModifiedOn 
	    {
		    get
		    {
			    return GetColumnValue<DateTime?>("ModifiedOn");
		    }
            set 
		    {
			    SetColumnValue("ModifiedOn", value);
            }
        }
	      
        [XmlAttribute("OldName")]
        [Bindable(true)]
        public string OldName 
	    {
		    get
		    {
			    return GetColumnValue<string>("OldName");
		    }
            set 
		    {
			    SetColumnValue("OldName", value);
            }
        }
	      
        [XmlAttribute("NewName")]
        [Bindable(true)]
        public string NewName 
	    {
		    get
		    {
			    return GetColumnValue<string>("NewName");
		    }
            set 
		    {
			    SetColumnValue("NewName", value);
            }
        }
	      
        [XmlAttribute("OldPhoneNumber")]
        [Bindable(true)]
        public string OldPhoneNumber 
	    {
		    get
		    {
			    return GetColumnValue<string>("OldPhoneNumber");
		    }
            set 
		    {
			    SetColumnValue("OldPhoneNumber", value);
            }
        }
	      
        [XmlAttribute("NewPhoneNumber")]
        [Bindable(true)]
        public string NewPhoneNumber 
	    {
		    get
		    {
			    return GetColumnValue<string>("NewPhoneNumber");
		    }
            set 
		    {
			    SetColumnValue("NewPhoneNumber", value);
            }
        }
	    
	    #endregion 
        #region Typed Columns
        
        public static TableSchema.TableColumn
        MoveIDColumn { get { return Schema.Columns[0]; } }
        
        public static TableSchema.TableColumn
        MoverDateColumn { get { return Schema.Columns[1]; } }
        
        public static TableSchema.TableColumn
        MoverMemberIDOldColumn { get { return Schema.Columns[2]; } }
        
        public static TableSchema.TableColumn
        MoverMemberIDNewColumn { get { return Schema.Columns[3]; } }
        
        public static TableSchema.TableColumn
        MoverMemberIDPointColumn { get { return Schema.Columns[4]; } }
        
        public static TableSchema.TableColumn
        CreatedByColumn { get { return Schema.Columns[5]; } }
        
        public static TableSchema.TableColumn
        CreatedOnColumn { get { return Schema.Columns[6]; } }
        
        public static TableSchema.TableColumn
        ModifiedByColumn { get { return Schema.Columns[7]; } }
        
        public static TableSchema.TableColumn
        ModifiedOnColumn { get { return Schema.Columns[8]; } }
        
        public static TableSchema.TableColumn
        OldNameColumn { get { return Schema.Columns[9]; } }
        
        public static TableSchema.TableColumn
        NewNameColumn { get { return Schema.Columns[10]; } }
        
        public static TableSchema.TableColumn
        OldPhoneNumberColumn { get { return Schema.Columns[11]; } }
        
        public static TableSchema.TableColumn
        NewPhoneNumberColumn { get { return Schema.Columns[12]; } }
        
        #endregion #region Columns Struct    
	    #region Columns Struct
	    public struct Columns
	    {
		    
		    
            public static string MoveID = @"MoveID";
            
            public static string MoverDate = @"MoverDate";
            
            public static string MoverMemberIDOld = @"MoverMemberIDOld";
            
            public static string MoverMemberIDNew = @"MoverMemberIDNew";
            
            public static string MoverMemberIDPoint = @"MoverMemberIDPoint";
            
            public static string CreatedBy = @"CreatedBy";
            
            public static string CreatedOn = @"CreatedOn";
            
            public static string ModifiedBy = @"ModifiedBy";
            
            public static string ModifiedOn = @"ModifiedOn";
            
            public static string OldName = @"OldName";
            
            public static string NewName = @"NewName";
            
            public static string OldPhoneNumber = @"OldPhoneNumber";
            
            public static string NewPhoneNumber = @"NewPhoneNumber";
            
	    }
	    #endregion
	    
	    
	    #region IAbstractRecord Members
        public new CT GetColumnValue<CT>(string columnName) {
            return base.GetColumnValue<CT>(columnName);
        }
        public object GetColumnValue(string columnName) {
            return base.GetColumnValue<object>(columnName);
        }
        #endregion
	    
    }
}
