using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
 //Generated on 2013/6/11 23:04:46 by Administrator
// <auto-generated />
namespace Eleooo.DAL
{
	/// <summary>
	/// This is an ActiveRecord class which wraps the Sys_Location table.
	/// </summary>
	[Serializable]
	public partial class SysLocationSchema : TableSchema.Table
	{
        public static TableSchema.Table Schema
        {
            get
            {
                return new SysLocationSchema();
            }
        }
		#region .ctors and Default Settings
		
		public SysLocationSchema()
            :base("Sys_Location")
		{
		}
		
		#endregion
		
		#region Schema and Query Accessor	
		
		protected override void Initital() 
        {
			//Schema define
			this.Columns = new TableSchema.TableColumnCollection();
			this.SchemaName = @"dbo";
            this.TableType = TableType.Table;
			//columns
			
			TableSchema.TableColumn colvarId = new TableSchema.TableColumn(this);
			colvarId.ColumnName = "ID";
			colvarId.DataType = DbType.Int32;
			colvarId.MaxLength = 0;
			colvarId.AutoIncrement = true;
			colvarId.IsNullable = false;
			colvarId.IsPrimaryKey = true;
			colvarId.IsForeignKey = false;
			colvarId.IsReadOnly = false;
                
			colvarId.DefaultSetting = @"";
			colvarId.ForeignKeyTableName = "";
            colvarId.ApplyExtendedProperties();
			this.Columns.Add(colvarId);
			
			TableSchema.TableColumn colvarLocationName = new TableSchema.TableColumn(this);
			colvarLocationName.ColumnName = "LocationName";
			colvarLocationName.DataType = DbType.String;
			colvarLocationName.MaxLength = 50;
			colvarLocationName.AutoIncrement = false;
			colvarLocationName.IsNullable = true;
			colvarLocationName.IsPrimaryKey = false;
			colvarLocationName.IsForeignKey = false;
			colvarLocationName.IsReadOnly = false;
                
			colvarLocationName.DefaultSetting = @"";
			colvarLocationName.ForeignKeyTableName = "";
            colvarLocationName.ApplyExtendedProperties();
			this.Columns.Add(colvarLocationName);
			
			TableSchema.TableColumn colvarLocationIntro = new TableSchema.TableColumn(this);
			colvarLocationIntro.ColumnName = "LocationIntro";
			colvarLocationIntro.DataType = DbType.String;
			colvarLocationIntro.MaxLength = 500;
			colvarLocationIntro.AutoIncrement = false;
			colvarLocationIntro.IsNullable = true;
			colvarLocationIntro.IsPrimaryKey = false;
			colvarLocationIntro.IsForeignKey = false;
			colvarLocationIntro.IsReadOnly = false;
                
			colvarLocationIntro.DefaultSetting = @"";
			colvarLocationIntro.ForeignKeyTableName = "";
            colvarLocationIntro.ApplyExtendedProperties();
			this.Columns.Add(colvarLocationIntro);
			
			TableSchema.TableColumn colvarLocationContent = new TableSchema.TableColumn(this);
			colvarLocationContent.ColumnName = "LocationContent";
			colvarLocationContent.DataType = DbType.String;
			colvarLocationContent.MaxLength = 1073741823;
			colvarLocationContent.AutoIncrement = false;
			colvarLocationContent.IsNullable = true;
			colvarLocationContent.IsPrimaryKey = false;
			colvarLocationContent.IsForeignKey = false;
			colvarLocationContent.IsReadOnly = false;
                
			colvarLocationContent.DefaultSetting = @"";
			colvarLocationContent.ForeignKeyTableName = "";
            colvarLocationContent.ApplyExtendedProperties();
			this.Columns.Add(colvarLocationContent);
			
			TableSchema.TableColumn colvarLocationAddress = new TableSchema.TableColumn(this);
			colvarLocationAddress.ColumnName = "LocationAddress";
			colvarLocationAddress.DataType = DbType.String;
			colvarLocationAddress.MaxLength = 50;
			colvarLocationAddress.AutoIncrement = false;
			colvarLocationAddress.IsNullable = true;
			colvarLocationAddress.IsPrimaryKey = false;
			colvarLocationAddress.IsForeignKey = false;
			colvarLocationAddress.IsReadOnly = false;
                
			colvarLocationAddress.DefaultSetting = @"";
			colvarLocationAddress.ForeignKeyTableName = "";
            colvarLocationAddress.ApplyExtendedProperties();
			this.Columns.Add(colvarLocationAddress);
			
			TableSchema.TableColumn colvarLocationMan = new TableSchema.TableColumn(this);
			colvarLocationMan.ColumnName = "LocationMan";
			colvarLocationMan.DataType = DbType.String;
			colvarLocationMan.MaxLength = 50;
			colvarLocationMan.AutoIncrement = false;
			colvarLocationMan.IsNullable = true;
			colvarLocationMan.IsPrimaryKey = false;
			colvarLocationMan.IsForeignKey = false;
			colvarLocationMan.IsReadOnly = false;
                
			colvarLocationMan.DefaultSetting = @"";
			colvarLocationMan.ForeignKeyTableName = "";
            colvarLocationMan.ApplyExtendedProperties();
			this.Columns.Add(colvarLocationMan);
			
			TableSchema.TableColumn colvarCreatedBy = new TableSchema.TableColumn(this);
			colvarCreatedBy.ColumnName = "CreatedBy";
			colvarCreatedBy.DataType = DbType.Int32;
			colvarCreatedBy.MaxLength = 0;
			colvarCreatedBy.AutoIncrement = false;
			colvarCreatedBy.IsNullable = true;
			colvarCreatedBy.IsPrimaryKey = false;
			colvarCreatedBy.IsForeignKey = false;
			colvarCreatedBy.IsReadOnly = false;
                
			colvarCreatedBy.DefaultSetting = @"";
			colvarCreatedBy.ForeignKeyTableName = "";
            colvarCreatedBy.ApplyExtendedProperties();
			this.Columns.Add(colvarCreatedBy);
			
			TableSchema.TableColumn colvarCreatedOn = new TableSchema.TableColumn(this);
			colvarCreatedOn.ColumnName = "CreatedOn";
			colvarCreatedOn.DataType = DbType.DateTime;
			colvarCreatedOn.MaxLength = 0;
			colvarCreatedOn.AutoIncrement = false;
			colvarCreatedOn.IsNullable = true;
			colvarCreatedOn.IsPrimaryKey = false;
			colvarCreatedOn.IsForeignKey = false;
			colvarCreatedOn.IsReadOnly = false;
                
			colvarCreatedOn.DefaultSetting = @"";
			colvarCreatedOn.ForeignKeyTableName = "";
            colvarCreatedOn.ApplyExtendedProperties();
			this.Columns.Add(colvarCreatedOn);
			
			TableSchema.TableColumn colvarModifiedBy = new TableSchema.TableColumn(this);
			colvarModifiedBy.ColumnName = "ModifiedBy";
			colvarModifiedBy.DataType = DbType.Int32;
			colvarModifiedBy.MaxLength = 0;
			colvarModifiedBy.AutoIncrement = false;
			colvarModifiedBy.IsNullable = true;
			colvarModifiedBy.IsPrimaryKey = false;
			colvarModifiedBy.IsForeignKey = false;
			colvarModifiedBy.IsReadOnly = false;
                
			colvarModifiedBy.DefaultSetting = @"";
			colvarModifiedBy.ForeignKeyTableName = "";
            colvarModifiedBy.ApplyExtendedProperties();
			this.Columns.Add(colvarModifiedBy);
			
			TableSchema.TableColumn colvarModifiedOn = new TableSchema.TableColumn(this);
			colvarModifiedOn.ColumnName = "ModifiedOn";
			colvarModifiedOn.DataType = DbType.DateTime;
			colvarModifiedOn.MaxLength = 0;
			colvarModifiedOn.AutoIncrement = false;
			colvarModifiedOn.IsNullable = true;
			colvarModifiedOn.IsPrimaryKey = false;
			colvarModifiedOn.IsForeignKey = false;
			colvarModifiedOn.IsReadOnly = false;
                
			colvarModifiedOn.DefaultSetting = @"";
			colvarModifiedOn.ForeignKeyTableName = "";
            colvarModifiedOn.ApplyExtendedProperties();
			this.Columns.Add(colvarModifiedOn);
			
		}
		#endregion
	}
}