using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
 //Generated on 2013/6/22 19:46:28 by Administrator
// <auto-generated />
namespace Eleooo.DAL
{
	/// <summary>
	/// This is an ActiveRecord class which wraps the Sys_Reward table.
	/// </summary>
	[Serializable]
	public partial class SysRewardSchema : TableSchema.Table
	{
        public static TableSchema.Table Schema
        {
            get
            {
                return new SysRewardSchema();
            }
        }
		#region .ctors and Default Settings
		
		public SysRewardSchema()
            :base("Sys_Reward")
		{
		}
		
		#endregion
		
		#region Schema and Query Accessor	
		
		protected override void Initital() 
        {
			//Schema define
			this.Columns = new TableSchema.TableColumnCollection();
			this.SchemaName = @"dbo";
            this.TableType = TableType.Table;
			//columns
			
			TableSchema.TableColumn colvarRewardID = new TableSchema.TableColumn(this);
			colvarRewardID.ColumnName = "RewardID";
			colvarRewardID.DataType = DbType.Int32;
			colvarRewardID.MaxLength = 0;
			colvarRewardID.AutoIncrement = true;
			colvarRewardID.IsNullable = false;
			colvarRewardID.IsPrimaryKey = true;
			colvarRewardID.IsForeignKey = false;
			colvarRewardID.IsReadOnly = false;
                
			colvarRewardID.DefaultSetting = @"";
			colvarRewardID.ForeignKeyTableName = "";
            colvarRewardID.ApplyExtendedProperties();
			this.Columns.Add(colvarRewardID);
			
			TableSchema.TableColumn colvarRewardDate = new TableSchema.TableColumn(this);
			colvarRewardDate.ColumnName = "RewardDate";
			colvarRewardDate.DataType = DbType.DateTime;
			colvarRewardDate.MaxLength = 0;
			colvarRewardDate.AutoIncrement = false;
			colvarRewardDate.IsNullable = true;
			colvarRewardDate.IsPrimaryKey = false;
			colvarRewardDate.IsForeignKey = false;
			colvarRewardDate.IsReadOnly = false;
                
			colvarRewardDate.DefaultSetting = @"";
			colvarRewardDate.ForeignKeyTableName = "";
            colvarRewardDate.ApplyExtendedProperties();
			this.Columns.Add(colvarRewardDate);
			
			TableSchema.TableColumn colvarRewardEndDate = new TableSchema.TableColumn(this);
			colvarRewardEndDate.ColumnName = "RewardEndDate";
			colvarRewardEndDate.DataType = DbType.DateTime;
			colvarRewardEndDate.MaxLength = 0;
			colvarRewardEndDate.AutoIncrement = false;
			colvarRewardEndDate.IsNullable = true;
			colvarRewardEndDate.IsPrimaryKey = false;
			colvarRewardEndDate.IsForeignKey = false;
			colvarRewardEndDate.IsReadOnly = false;
                
			colvarRewardEndDate.DefaultSetting = @"";
			colvarRewardEndDate.ForeignKeyTableName = "";
            colvarRewardEndDate.ApplyExtendedProperties();
			this.Columns.Add(colvarRewardEndDate);
			
			TableSchema.TableColumn colvarRewardRate = new TableSchema.TableColumn(this);
			colvarRewardRate.ColumnName = "RewardRate";
			colvarRewardRate.DataType = DbType.Decimal;
			colvarRewardRate.MaxLength = 0;
			colvarRewardRate.AutoIncrement = false;
			colvarRewardRate.IsNullable = true;
			colvarRewardRate.IsPrimaryKey = false;
			colvarRewardRate.IsForeignKey = false;
			colvarRewardRate.IsReadOnly = false;
                
			colvarRewardRate.DefaultSetting = @"";
			colvarRewardRate.ForeignKeyTableName = "";
            colvarRewardRate.ApplyExtendedProperties();
			this.Columns.Add(colvarRewardRate);
			
			TableSchema.TableColumn colvarRewardFlag = new TableSchema.TableColumn(this);
			colvarRewardFlag.ColumnName = "RewardFlag";
			colvarRewardFlag.DataType = DbType.Int32;
			colvarRewardFlag.MaxLength = 0;
			colvarRewardFlag.AutoIncrement = false;
			colvarRewardFlag.IsNullable = true;
			colvarRewardFlag.IsPrimaryKey = false;
			colvarRewardFlag.IsForeignKey = false;
			colvarRewardFlag.IsReadOnly = false;
                
			colvarRewardFlag.DefaultSetting = @"";
			colvarRewardFlag.ForeignKeyTableName = "";
            colvarRewardFlag.ApplyExtendedProperties();
			this.Columns.Add(colvarRewardFlag);
			
			TableSchema.TableColumn colvarRewardMemo = new TableSchema.TableColumn(this);
			colvarRewardMemo.ColumnName = "RewardMemo";
			colvarRewardMemo.DataType = DbType.AnsiString;
			colvarRewardMemo.MaxLength = 2147483647;
			colvarRewardMemo.AutoIncrement = false;
			colvarRewardMemo.IsNullable = true;
			colvarRewardMemo.IsPrimaryKey = false;
			colvarRewardMemo.IsForeignKey = false;
			colvarRewardMemo.IsReadOnly = false;
                
			colvarRewardMemo.DefaultSetting = @"";
			colvarRewardMemo.ForeignKeyTableName = "";
            colvarRewardMemo.ApplyExtendedProperties();
			this.Columns.Add(colvarRewardMemo);
			
		}
		#endregion
	}
}