using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
 //Generated on 2013/6/22 19:46:29 by Administrator
// <auto-generated />
namespace Eleooo.DAL
{
	/// <summary>
	/// This is an ActiveRecord class which wraps the Sys_Support table.
	/// </summary>
	[Serializable]
	public partial class SysSupportSchema : TableSchema.Table
	{
        public static TableSchema.Table Schema
        {
            get
            {
                return new SysSupportSchema();
            }
        }
		#region .ctors and Default Settings
		
		public SysSupportSchema()
            :base("Sys_Support")
		{
		}
		
		#endregion
		
		#region Schema and Query Accessor	
		
		protected override void Initital() 
        {
			//Schema define
			this.Columns = new TableSchema.TableColumnCollection();
			this.SchemaName = @"dbo";
            this.TableType = TableType.Table;
			//columns
			
			TableSchema.TableColumn colvarSupportId = new TableSchema.TableColumn(this);
			colvarSupportId.ColumnName = "Support_ID";
			colvarSupportId.DataType = DbType.Int32;
			colvarSupportId.MaxLength = 0;
			colvarSupportId.AutoIncrement = true;
			colvarSupportId.IsNullable = false;
			colvarSupportId.IsPrimaryKey = true;
			colvarSupportId.IsForeignKey = false;
			colvarSupportId.IsReadOnly = false;
                
			colvarSupportId.DefaultSetting = @"";
			colvarSupportId.ForeignKeyTableName = "";
            colvarSupportId.ApplyExtendedProperties();
			this.Columns.Add(colvarSupportId);
			
			TableSchema.TableColumn colvarSupportFid = new TableSchema.TableColumn(this);
			colvarSupportFid.ColumnName = "Support_FID";
			colvarSupportFid.DataType = DbType.Int32;
			colvarSupportFid.MaxLength = 0;
			colvarSupportFid.AutoIncrement = false;
			colvarSupportFid.IsNullable = false;
			colvarSupportFid.IsPrimaryKey = false;
			colvarSupportFid.IsForeignKey = false;
			colvarSupportFid.IsReadOnly = false;
                
			colvarSupportFid.DefaultSetting = @"";
			colvarSupportFid.ForeignKeyTableName = "";
            colvarSupportFid.ApplyExtendedProperties();
			this.Columns.Add(colvarSupportFid);
			
			TableSchema.TableColumn colvarSupportTid = new TableSchema.TableColumn(this);
			colvarSupportTid.ColumnName = "Support_TID";
			colvarSupportTid.DataType = DbType.Int32;
			colvarSupportTid.MaxLength = 0;
			colvarSupportTid.AutoIncrement = false;
			colvarSupportTid.IsNullable = false;
			colvarSupportTid.IsPrimaryKey = false;
			colvarSupportTid.IsForeignKey = false;
			colvarSupportTid.IsReadOnly = false;
                
			colvarSupportTid.DefaultSetting = @"";
			colvarSupportTid.ForeignKeyTableName = "";
            colvarSupportTid.ApplyExtendedProperties();
			this.Columns.Add(colvarSupportTid);
			
			TableSchema.TableColumn colvarSupportItem = new TableSchema.TableColumn(this);
			colvarSupportItem.ColumnName = "Support_Item";
			colvarSupportItem.DataType = DbType.Int32;
			colvarSupportItem.MaxLength = 0;
			colvarSupportItem.AutoIncrement = false;
			colvarSupportItem.IsNullable = false;
			colvarSupportItem.IsPrimaryKey = false;
			colvarSupportItem.IsForeignKey = false;
			colvarSupportItem.IsReadOnly = false;
                
			colvarSupportItem.DefaultSetting = @"";
			colvarSupportItem.ForeignKeyTableName = "";
            colvarSupportItem.ApplyExtendedProperties();
			this.Columns.Add(colvarSupportItem);
			
			TableSchema.TableColumn colvarSupportType = new TableSchema.TableColumn(this);
			colvarSupportType.ColumnName = "Support_Type";
			colvarSupportType.DataType = DbType.Int32;
			colvarSupportType.MaxLength = 0;
			colvarSupportType.AutoIncrement = false;
			colvarSupportType.IsNullable = false;
			colvarSupportType.IsPrimaryKey = false;
			colvarSupportType.IsForeignKey = false;
			colvarSupportType.IsReadOnly = false;
                
			colvarSupportType.DefaultSetting = @"";
			colvarSupportType.ForeignKeyTableName = "";
            colvarSupportType.ApplyExtendedProperties();
			this.Columns.Add(colvarSupportType);
			
			TableSchema.TableColumn colvarSupportProductID = new TableSchema.TableColumn(this);
			colvarSupportProductID.ColumnName = "Support_ProductID";
			colvarSupportProductID.DataType = DbType.Int32;
			colvarSupportProductID.MaxLength = 0;
			colvarSupportProductID.AutoIncrement = false;
			colvarSupportProductID.IsNullable = false;
			colvarSupportProductID.IsPrimaryKey = false;
			colvarSupportProductID.IsForeignKey = false;
			colvarSupportProductID.IsReadOnly = false;
                
			colvarSupportProductID.DefaultSetting = @"";
			colvarSupportProductID.ForeignKeyTableName = "";
            colvarSupportProductID.ApplyExtendedProperties();
			this.Columns.Add(colvarSupportProductID);
			
			TableSchema.TableColumn colvarSupportSubject = new TableSchema.TableColumn(this);
			colvarSupportSubject.ColumnName = "Support_Subject";
			colvarSupportSubject.DataType = DbType.String;
			colvarSupportSubject.MaxLength = 200;
			colvarSupportSubject.AutoIncrement = false;
			colvarSupportSubject.IsNullable = false;
			colvarSupportSubject.IsPrimaryKey = false;
			colvarSupportSubject.IsForeignKey = false;
			colvarSupportSubject.IsReadOnly = false;
                
			colvarSupportSubject.DefaultSetting = @"";
			colvarSupportSubject.ForeignKeyTableName = "";
            colvarSupportSubject.ApplyExtendedProperties();
			this.Columns.Add(colvarSupportSubject);
			
			TableSchema.TableColumn colvarSupportContent = new TableSchema.TableColumn(this);
			colvarSupportContent.ColumnName = "Support_Content";
			colvarSupportContent.DataType = DbType.String;
			colvarSupportContent.MaxLength = 2000;
			colvarSupportContent.AutoIncrement = false;
			colvarSupportContent.IsNullable = true;
			colvarSupportContent.IsPrimaryKey = false;
			colvarSupportContent.IsForeignKey = false;
			colvarSupportContent.IsReadOnly = false;
                
			colvarSupportContent.DefaultSetting = @"";
			colvarSupportContent.ForeignKeyTableName = "";
            colvarSupportContent.ApplyExtendedProperties();
			this.Columns.Add(colvarSupportContent);
			
			TableSchema.TableColumn colvarSupportAttach = new TableSchema.TableColumn(this);
			colvarSupportAttach.ColumnName = "Support_Attach";
			colvarSupportAttach.DataType = DbType.String;
			colvarSupportAttach.MaxLength = 50;
			colvarSupportAttach.AutoIncrement = false;
			colvarSupportAttach.IsNullable = true;
			colvarSupportAttach.IsPrimaryKey = false;
			colvarSupportAttach.IsForeignKey = false;
			colvarSupportAttach.IsReadOnly = false;
                
			colvarSupportAttach.DefaultSetting = @"";
			colvarSupportAttach.ForeignKeyTableName = "";
            colvarSupportAttach.ApplyExtendedProperties();
			this.Columns.Add(colvarSupportAttach);
			
			TableSchema.TableColumn colvarSupportPhoto = new TableSchema.TableColumn(this);
			colvarSupportPhoto.ColumnName = "Support_Photo";
			colvarSupportPhoto.DataType = DbType.String;
			colvarSupportPhoto.MaxLength = 50;
			colvarSupportPhoto.AutoIncrement = false;
			colvarSupportPhoto.IsNullable = true;
			colvarSupportPhoto.IsPrimaryKey = false;
			colvarSupportPhoto.IsForeignKey = false;
			colvarSupportPhoto.IsReadOnly = false;
                
			colvarSupportPhoto.DefaultSetting = @"";
			colvarSupportPhoto.ForeignKeyTableName = "";
            colvarSupportPhoto.ApplyExtendedProperties();
			this.Columns.Add(colvarSupportPhoto);
			
			TableSchema.TableColumn colvarSupportIsRead = new TableSchema.TableColumn(this);
			colvarSupportIsRead.ColumnName = "Support_IsRead";
			colvarSupportIsRead.DataType = DbType.Boolean;
			colvarSupportIsRead.MaxLength = 0;
			colvarSupportIsRead.AutoIncrement = false;
			colvarSupportIsRead.IsNullable = false;
			colvarSupportIsRead.IsPrimaryKey = false;
			colvarSupportIsRead.IsForeignKey = false;
			colvarSupportIsRead.IsReadOnly = false;
                
			colvarSupportIsRead.DefaultSetting = @"";
			colvarSupportIsRead.ForeignKeyTableName = "";
            colvarSupportIsRead.ApplyExtendedProperties();
			this.Columns.Add(colvarSupportIsRead);
			
			TableSchema.TableColumn colvarSupportRating = new TableSchema.TableColumn(this);
			colvarSupportRating.ColumnName = "Support_Rating";
			colvarSupportRating.DataType = DbType.Int32;
			colvarSupportRating.MaxLength = 0;
			colvarSupportRating.AutoIncrement = false;
			colvarSupportRating.IsNullable = true;
			colvarSupportRating.IsPrimaryKey = false;
			colvarSupportRating.IsForeignKey = false;
			colvarSupportRating.IsReadOnly = false;
                
			colvarSupportRating.DefaultSetting = @"";
			colvarSupportRating.ForeignKeyTableName = "";
            colvarSupportRating.ApplyExtendedProperties();
			this.Columns.Add(colvarSupportRating);
			
			TableSchema.TableColumn colvarSupportRatingReason = new TableSchema.TableColumn(this);
			colvarSupportRatingReason.ColumnName = "Support_RatingReason";
			colvarSupportRatingReason.DataType = DbType.String;
			colvarSupportRatingReason.MaxLength = 200;
			colvarSupportRatingReason.AutoIncrement = false;
			colvarSupportRatingReason.IsNullable = true;
			colvarSupportRatingReason.IsPrimaryKey = false;
			colvarSupportRatingReason.IsForeignKey = false;
			colvarSupportRatingReason.IsReadOnly = false;
                
			colvarSupportRatingReason.DefaultSetting = @"";
			colvarSupportRatingReason.ForeignKeyTableName = "";
            colvarSupportRatingReason.ApplyExtendedProperties();
			this.Columns.Add(colvarSupportRatingReason);
			
			TableSchema.TableColumn colvarSupportStatus = new TableSchema.TableColumn(this);
			colvarSupportStatus.ColumnName = "Support_Status";
			colvarSupportStatus.DataType = DbType.Int32;
			colvarSupportStatus.MaxLength = 0;
			colvarSupportStatus.AutoIncrement = false;
			colvarSupportStatus.IsNullable = false;
			colvarSupportStatus.IsPrimaryKey = false;
			colvarSupportStatus.IsForeignKey = false;
			colvarSupportStatus.IsReadOnly = false;
                
			colvarSupportStatus.DefaultSetting = @"";
			colvarSupportStatus.ForeignKeyTableName = "";
            colvarSupportStatus.ApplyExtendedProperties();
			this.Columns.Add(colvarSupportStatus);
			
			TableSchema.TableColumn colvarSupportDate = new TableSchema.TableColumn(this);
			colvarSupportDate.ColumnName = "Support_Date";
			colvarSupportDate.DataType = DbType.DateTime;
			colvarSupportDate.MaxLength = 0;
			colvarSupportDate.AutoIncrement = false;
			colvarSupportDate.IsNullable = false;
			colvarSupportDate.IsPrimaryKey = false;
			colvarSupportDate.IsForeignKey = false;
			colvarSupportDate.IsReadOnly = false;
                
			colvarSupportDate.DefaultSetting = @"";
			colvarSupportDate.ForeignKeyTableName = "";
            colvarSupportDate.ApplyExtendedProperties();
			this.Columns.Add(colvarSupportDate);
			
			TableSchema.TableColumn colvarSupportDateReply = new TableSchema.TableColumn(this);
			colvarSupportDateReply.ColumnName = "Support_DateReply";
			colvarSupportDateReply.DataType = DbType.DateTime;
			colvarSupportDateReply.MaxLength = 0;
			colvarSupportDateReply.AutoIncrement = false;
			colvarSupportDateReply.IsNullable = true;
			colvarSupportDateReply.IsPrimaryKey = false;
			colvarSupportDateReply.IsForeignKey = false;
			colvarSupportDateReply.IsReadOnly = false;
                
			colvarSupportDateReply.DefaultSetting = @"";
			colvarSupportDateReply.ForeignKeyTableName = "";
            colvarSupportDateReply.ApplyExtendedProperties();
			this.Columns.Add(colvarSupportDateReply);
			
			TableSchema.TableColumn colvarSupportDateFinish = new TableSchema.TableColumn(this);
			colvarSupportDateFinish.ColumnName = "Support_DateFinish";
			colvarSupportDateFinish.DataType = DbType.DateTime;
			colvarSupportDateFinish.MaxLength = 0;
			colvarSupportDateFinish.AutoIncrement = false;
			colvarSupportDateFinish.IsNullable = true;
			colvarSupportDateFinish.IsPrimaryKey = false;
			colvarSupportDateFinish.IsForeignKey = false;
			colvarSupportDateFinish.IsReadOnly = false;
                
			colvarSupportDateFinish.DefaultSetting = @"";
			colvarSupportDateFinish.ForeignKeyTableName = "";
            colvarSupportDateFinish.ApplyExtendedProperties();
			this.Columns.Add(colvarSupportDateFinish);
			
			TableSchema.TableColumn colvarCreatedBy = new TableSchema.TableColumn(this);
			colvarCreatedBy.ColumnName = "CreatedBy";
			colvarCreatedBy.DataType = DbType.Int32;
			colvarCreatedBy.MaxLength = 0;
			colvarCreatedBy.AutoIncrement = false;
			colvarCreatedBy.IsNullable = true;
			colvarCreatedBy.IsPrimaryKey = false;
			colvarCreatedBy.IsForeignKey = false;
			colvarCreatedBy.IsReadOnly = false;
                
			colvarCreatedBy.DefaultSetting = @"";
			colvarCreatedBy.ForeignKeyTableName = "";
            colvarCreatedBy.ApplyExtendedProperties();
			this.Columns.Add(colvarCreatedBy);
			
			TableSchema.TableColumn colvarCreatedOn = new TableSchema.TableColumn(this);
			colvarCreatedOn.ColumnName = "CreatedOn";
			colvarCreatedOn.DataType = DbType.DateTime;
			colvarCreatedOn.MaxLength = 0;
			colvarCreatedOn.AutoIncrement = false;
			colvarCreatedOn.IsNullable = true;
			colvarCreatedOn.IsPrimaryKey = false;
			colvarCreatedOn.IsForeignKey = false;
			colvarCreatedOn.IsReadOnly = false;
                
			colvarCreatedOn.DefaultSetting = @"";
			colvarCreatedOn.ForeignKeyTableName = "";
            colvarCreatedOn.ApplyExtendedProperties();
			this.Columns.Add(colvarCreatedOn);
			
			TableSchema.TableColumn colvarModifiedBy = new TableSchema.TableColumn(this);
			colvarModifiedBy.ColumnName = "ModifiedBy";
			colvarModifiedBy.DataType = DbType.Int32;
			colvarModifiedBy.MaxLength = 0;
			colvarModifiedBy.AutoIncrement = false;
			colvarModifiedBy.IsNullable = true;
			colvarModifiedBy.IsPrimaryKey = false;
			colvarModifiedBy.IsForeignKey = false;
			colvarModifiedBy.IsReadOnly = false;
                
			colvarModifiedBy.DefaultSetting = @"";
			colvarModifiedBy.ForeignKeyTableName = "";
            colvarModifiedBy.ApplyExtendedProperties();
			this.Columns.Add(colvarModifiedBy);
			
			TableSchema.TableColumn colvarModifiedOn = new TableSchema.TableColumn(this);
			colvarModifiedOn.ColumnName = "ModifiedOn";
			colvarModifiedOn.DataType = DbType.DateTime;
			colvarModifiedOn.MaxLength = 0;
			colvarModifiedOn.AutoIncrement = false;
			colvarModifiedOn.IsNullable = true;
			colvarModifiedOn.IsPrimaryKey = false;
			colvarModifiedOn.IsForeignKey = false;
			colvarModifiedOn.IsReadOnly = false;
                
			colvarModifiedOn.DefaultSetting = @"";
			colvarModifiedOn.ForeignKeyTableName = "";
            colvarModifiedOn.ApplyExtendedProperties();
			this.Columns.Add(colvarModifiedOn);
			
		}
		#endregion
	}
}