using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
 //Generated on 2013/7/19 0:44:48 by Administrator
// <auto-generated />
namespace Eleooo.DAL
{
	/// <summary>
	/// This is an ActiveRecord class which wraps the v_Payment_Date table.
	/// </summary>
	[Serializable]
	public partial class VPaymentDateSchema : TableSchema.Table
	{
        public static TableSchema.Table Schema
        {
            get
            {
                return new VPaymentDateSchema();
            }
        }
		#region .ctors and Default Settings
		
		public VPaymentDateSchema()
            :base("v_Payment_Date")
		{
		}
		
		#endregion
		
		#region Schema and Query Accessor	
		
		protected override void Initital() 
        {
			//Schema define
			this.Columns = new TableSchema.TableColumnCollection();
			this.SchemaName = @"dbo";
            this.TableType = TableType.Table;
			//columns
			
			TableSchema.TableColumn colvarOrderdate = new TableSchema.TableColumn(this);
			colvarOrderdate.ColumnName = "Orderdate";
			colvarOrderdate.DataType = DbType.DateTime;
			colvarOrderdate.MaxLength = 0;
			colvarOrderdate.AutoIncrement = false;
			colvarOrderdate.IsNullable = true;
			colvarOrderdate.IsPrimaryKey = false;
			colvarOrderdate.IsForeignKey = false;
			colvarOrderdate.IsReadOnly = false;
                
			colvarOrderdate.DefaultSetting = @"";
			colvarOrderdate.ForeignKeyTableName = "";
            colvarOrderdate.ApplyExtendedProperties();
			this.Columns.Add(colvarOrderdate);
			
		}
		#endregion
	}
}