using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
 //Generated on 2013/6/18 20:31:45 by Administrator
// <auto-generated />
namespace Eleooo.DAL
{
	/// <summary>
	/// This is an ActiveRecord class which wraps the v_Sys_Member_Ads_Sum table.
	/// </summary>
	[Serializable]
	public partial class VSysMemberAdsSumSchema : TableSchema.Table
	{
        public static TableSchema.Table Schema
        {
            get
            {
                return new VSysMemberAdsSumSchema();
            }
        }
		#region .ctors and Default Settings
		
		public VSysMemberAdsSumSchema()
            :base("v_Sys_Member_Ads_Sum")
		{
		}
		
		#endregion
		
		#region Schema and Query Accessor	
		
		protected override void Initital() 
        {
			//Schema define
			this.Columns = new TableSchema.TableColumnCollection();
			this.SchemaName = @"dbo";
            this.TableType = TableType.Table;
			//columns
			
			TableSchema.TableColumn colvarAdsCount = new TableSchema.TableColumn(this);
			colvarAdsCount.ColumnName = "AdsCount";
			colvarAdsCount.DataType = DbType.Int32;
			colvarAdsCount.MaxLength = 0;
			colvarAdsCount.AutoIncrement = false;
			colvarAdsCount.IsNullable = true;
			colvarAdsCount.IsPrimaryKey = false;
			colvarAdsCount.IsForeignKey = false;
			colvarAdsCount.IsReadOnly = false;
                
			colvarAdsCount.DefaultSetting = @"";
			colvarAdsCount.ForeignKeyTableName = "";
            colvarAdsCount.ApplyExtendedProperties();
			this.Columns.Add(colvarAdsCount);
			
			TableSchema.TableColumn colvarAdsPointSum = new TableSchema.TableColumn(this);
			colvarAdsPointSum.ColumnName = "AdsPointSum";
			colvarAdsPointSum.DataType = DbType.Decimal;
			colvarAdsPointSum.MaxLength = 0;
			colvarAdsPointSum.AutoIncrement = false;
			colvarAdsPointSum.IsNullable = true;
			colvarAdsPointSum.IsPrimaryKey = false;
			colvarAdsPointSum.IsForeignKey = false;
			colvarAdsPointSum.IsReadOnly = false;
                
			colvarAdsPointSum.DefaultSetting = @"";
			colvarAdsPointSum.ForeignKeyTableName = "";
            colvarAdsPointSum.ApplyExtendedProperties();
			this.Columns.Add(colvarAdsPointSum);
			
			TableSchema.TableColumn colvarAdsMemberID = new TableSchema.TableColumn(this);
			colvarAdsMemberID.ColumnName = "AdsMemberID";
			colvarAdsMemberID.DataType = DbType.Int32;
			colvarAdsMemberID.MaxLength = 0;
			colvarAdsMemberID.AutoIncrement = false;
			colvarAdsMemberID.IsNullable = true;
			colvarAdsMemberID.IsPrimaryKey = false;
			colvarAdsMemberID.IsForeignKey = false;
			colvarAdsMemberID.IsReadOnly = false;
                
			colvarAdsMemberID.DefaultSetting = @"";
			colvarAdsMemberID.ForeignKeyTableName = "";
            colvarAdsMemberID.ApplyExtendedProperties();
			this.Columns.Add(colvarAdsMemberID);
			
			TableSchema.TableColumn colvarCompanyAdsID = new TableSchema.TableColumn(this);
			colvarCompanyAdsID.ColumnName = "CompanyAdsID";
			colvarCompanyAdsID.DataType = DbType.Int32;
			colvarCompanyAdsID.MaxLength = 0;
			colvarCompanyAdsID.AutoIncrement = false;
			colvarCompanyAdsID.IsNullable = true;
			colvarCompanyAdsID.IsPrimaryKey = false;
			colvarCompanyAdsID.IsForeignKey = false;
			colvarCompanyAdsID.IsReadOnly = false;
                
			colvarCompanyAdsID.DefaultSetting = @"";
			colvarCompanyAdsID.ForeignKeyTableName = "";
            colvarCompanyAdsID.ApplyExtendedProperties();
			this.Columns.Add(colvarCompanyAdsID);
			
			TableSchema.TableColumn colvarCompanyID = new TableSchema.TableColumn(this);
			colvarCompanyID.ColumnName = "CompanyID";
			colvarCompanyID.DataType = DbType.Int32;
			colvarCompanyID.MaxLength = 0;
			colvarCompanyID.AutoIncrement = false;
			colvarCompanyID.IsNullable = true;
			colvarCompanyID.IsPrimaryKey = false;
			colvarCompanyID.IsForeignKey = false;
			colvarCompanyID.IsReadOnly = false;
                
			colvarCompanyID.DefaultSetting = @"";
			colvarCompanyID.ForeignKeyTableName = "";
            colvarCompanyID.ApplyExtendedProperties();
			this.Columns.Add(colvarCompanyID);
			
			TableSchema.TableColumn colvarAdsClickDate = new TableSchema.TableColumn(this);
			colvarAdsClickDate.ColumnName = "AdsClickDate";
			colvarAdsClickDate.DataType = DbType.DateTime;
			colvarAdsClickDate.MaxLength = 0;
			colvarAdsClickDate.AutoIncrement = false;
			colvarAdsClickDate.IsNullable = true;
			colvarAdsClickDate.IsPrimaryKey = false;
			colvarAdsClickDate.IsForeignKey = false;
			colvarAdsClickDate.IsReadOnly = false;
                
			colvarAdsClickDate.DefaultSetting = @"";
			colvarAdsClickDate.ForeignKeyTableName = "";
            colvarAdsClickDate.ApplyExtendedProperties();
			this.Columns.Add(colvarAdsClickDate);
			
			TableSchema.TableColumn colvarAdsTitle = new TableSchema.TableColumn(this);
			colvarAdsTitle.ColumnName = "AdsTitle";
			colvarAdsTitle.DataType = DbType.String;
			colvarAdsTitle.MaxLength = 500;
			colvarAdsTitle.AutoIncrement = false;
			colvarAdsTitle.IsNullable = true;
			colvarAdsTitle.IsPrimaryKey = false;
			colvarAdsTitle.IsForeignKey = false;
			colvarAdsTitle.IsReadOnly = false;
                
			colvarAdsTitle.DefaultSetting = @"";
			colvarAdsTitle.ForeignKeyTableName = "";
            colvarAdsTitle.ApplyExtendedProperties();
			this.Columns.Add(colvarAdsTitle);
			
			TableSchema.TableColumn colvarOrderSum = new TableSchema.TableColumn(this);
			colvarOrderSum.ColumnName = "OrderSum";
			colvarOrderSum.DataType = DbType.Decimal;
			colvarOrderSum.MaxLength = 0;
			colvarOrderSum.AutoIncrement = false;
			colvarOrderSum.IsNullable = true;
			colvarOrderSum.IsPrimaryKey = false;
			colvarOrderSum.IsForeignKey = false;
			colvarOrderSum.IsReadOnly = false;
                
			colvarOrderSum.DefaultSetting = @"";
			colvarOrderSum.ForeignKeyTableName = "";
            colvarOrderSum.ApplyExtendedProperties();
			this.Columns.Add(colvarOrderSum);
			
			TableSchema.TableColumn colvarMemberPhoneNumber = new TableSchema.TableColumn(this);
			colvarMemberPhoneNumber.ColumnName = "MemberPhoneNumber";
			colvarMemberPhoneNumber.DataType = DbType.String;
			colvarMemberPhoneNumber.MaxLength = 50;
			colvarMemberPhoneNumber.AutoIncrement = false;
			colvarMemberPhoneNumber.IsNullable = false;
			colvarMemberPhoneNumber.IsPrimaryKey = false;
			colvarMemberPhoneNumber.IsForeignKey = false;
			colvarMemberPhoneNumber.IsReadOnly = false;
                
			colvarMemberPhoneNumber.DefaultSetting = @"";
			colvarMemberPhoneNumber.ForeignKeyTableName = "";
            colvarMemberPhoneNumber.ApplyExtendedProperties();
			this.Columns.Add(colvarMemberPhoneNumber);
			
			TableSchema.TableColumn colvarMemberFullname = new TableSchema.TableColumn(this);
			colvarMemberFullname.ColumnName = "MemberFullname";
			colvarMemberFullname.DataType = DbType.String;
			colvarMemberFullname.MaxLength = 50;
			colvarMemberFullname.AutoIncrement = false;
			colvarMemberFullname.IsNullable = true;
			colvarMemberFullname.IsPrimaryKey = false;
			colvarMemberFullname.IsForeignKey = false;
			colvarMemberFullname.IsReadOnly = false;
                
			colvarMemberFullname.DefaultSetting = @"";
			colvarMemberFullname.ForeignKeyTableName = "";
            colvarMemberFullname.ApplyExtendedProperties();
			this.Columns.Add(colvarMemberFullname);
			
			TableSchema.TableColumn colvarCompanyName = new TableSchema.TableColumn(this);
			colvarCompanyName.ColumnName = "CompanyName";
			colvarCompanyName.DataType = DbType.String;
			colvarCompanyName.MaxLength = 50;
			colvarCompanyName.AutoIncrement = false;
			colvarCompanyName.IsNullable = true;
			colvarCompanyName.IsPrimaryKey = false;
			colvarCompanyName.IsForeignKey = false;
			colvarCompanyName.IsReadOnly = false;
                
			colvarCompanyName.DefaultSetting = @"";
			colvarCompanyName.ForeignKeyTableName = "";
            colvarCompanyName.ApplyExtendedProperties();
			this.Columns.Add(colvarCompanyName);
			
			TableSchema.TableColumn colvarMemberCompanyID = new TableSchema.TableColumn(this);
			colvarMemberCompanyID.ColumnName = "MemberCompanyID";
			colvarMemberCompanyID.DataType = DbType.Int32;
			colvarMemberCompanyID.MaxLength = 0;
			colvarMemberCompanyID.AutoIncrement = false;
			colvarMemberCompanyID.IsNullable = true;
			colvarMemberCompanyID.IsPrimaryKey = false;
			colvarMemberCompanyID.IsForeignKey = false;
			colvarMemberCompanyID.IsReadOnly = false;
                
			colvarMemberCompanyID.DefaultSetting = @"";
			colvarMemberCompanyID.ForeignKeyTableName = "";
            colvarMemberCompanyID.ApplyExtendedProperties();
			this.Columns.Add(colvarMemberCompanyID);
			
			TableSchema.TableColumn colvarAdsDate = new TableSchema.TableColumn(this);
			colvarAdsDate.ColumnName = "AdsDate";
			colvarAdsDate.DataType = DbType.DateTime;
			colvarAdsDate.MaxLength = 0;
			colvarAdsDate.AutoIncrement = false;
			colvarAdsDate.IsNullable = true;
			colvarAdsDate.IsPrimaryKey = false;
			colvarAdsDate.IsForeignKey = false;
			colvarAdsDate.IsReadOnly = false;
                
			colvarAdsDate.DefaultSetting = @"";
			colvarAdsDate.ForeignKeyTableName = "";
            colvarAdsDate.ApplyExtendedProperties();
			this.Columns.Add(colvarAdsDate);
			
			TableSchema.TableColumn colvarAdsEndDate = new TableSchema.TableColumn(this);
			colvarAdsEndDate.ColumnName = "AdsEndDate";
			colvarAdsEndDate.DataType = DbType.DateTime;
			colvarAdsEndDate.MaxLength = 0;
			colvarAdsEndDate.AutoIncrement = false;
			colvarAdsEndDate.IsNullable = true;
			colvarAdsEndDate.IsPrimaryKey = false;
			colvarAdsEndDate.IsForeignKey = false;
			colvarAdsEndDate.IsReadOnly = false;
                
			colvarAdsEndDate.DefaultSetting = @"";
			colvarAdsEndDate.ForeignKeyTableName = "";
            colvarAdsEndDate.ApplyExtendedProperties();
			this.Columns.Add(colvarAdsEndDate);
			
		}
		#endregion
	}
}