using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Eleooo.DAL
{
    /// <summary>
    /// Controller class for Sys_Ads_ClickSetting
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class SysAdsClickSettingController
    {
        // Preload our schema..
        SysAdsClickSetting thisSchemaLoad = new SysAdsClickSetting();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public SysAdsClickSettingCollection FetchAll()
        {
            SysAdsClickSettingCollection coll = new SysAdsClickSettingCollection();
            Query qry = new Query(SysAdsClickSetting.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public SysAdsClickSettingCollection FetchByID(object Id)
        {
            SysAdsClickSettingCollection coll = new SysAdsClickSettingCollection().Where("ID", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public SysAdsClickSettingCollection FetchByQuery(Query qry)
        {
            SysAdsClickSettingCollection coll = new SysAdsClickSettingCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (SysAdsClickSetting.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (SysAdsClickSetting.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(decimal? OrderSumLimit,int? ClickCountLimit)
	    {
		    SysAdsClickSetting item = new SysAdsClickSetting();
		    
            item.OrderSumLimit = OrderSumLimit;
            
            item.ClickCountLimit = ClickCountLimit;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,decimal? OrderSumLimit,int? ClickCountLimit)
	    {
		    SysAdsClickSetting item = new SysAdsClickSetting();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.OrderSumLimit = OrderSumLimit;
				
			item.ClickCountLimit = ClickCountLimit;
				
	        item.Save(UserName);
	    }
    }
}
