using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Eleooo.DAL
{
    /// <summary>
    /// Controller class for Sys_Company_Member
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class SysCompanyMemberController
    {
        // Preload our schema..
        SysCompanyMember thisSchemaLoad = new SysCompanyMember();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public SysCompanyMemberCollection FetchAll()
        {
            SysCompanyMemberCollection coll = new SysCompanyMemberCollection();
            Query qry = new Query(SysCompanyMember.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public SysCompanyMemberCollection FetchByID(object Id)
        {
            SysCompanyMemberCollection coll = new SysCompanyMemberCollection().Where("ID", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public SysCompanyMemberCollection FetchByQuery(Query qry)
        {
            SysCompanyMemberCollection coll = new SysCompanyMemberCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (SysCompanyMember.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (SysCompanyMember.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int? CmCompanyID,int? CmMemberID,string CmMemberLevel,decimal? CmMemberRate,decimal? CmBalanceSum,decimal? CmBalanceCash,decimal? CmBalancePoint,DateTime? CmDate,int? CreatedBy,DateTime? CreatedOn,int? ModifiedBy,DateTime? ModifiedOn)
	    {
		    SysCompanyMember item = new SysCompanyMember();
		    
            item.CmCompanyID = CmCompanyID;
            
            item.CmMemberID = CmMemberID;
            
            item.CmMemberLevel = CmMemberLevel;
            
            item.CmMemberRate = CmMemberRate;
            
            item.CmBalanceSum = CmBalanceSum;
            
            item.CmBalanceCash = CmBalanceCash;
            
            item.CmBalancePoint = CmBalancePoint;
            
            item.CmDate = CmDate;
            
            item.CreatedBy = CreatedBy;
            
            item.CreatedOn = CreatedOn;
            
            item.ModifiedBy = ModifiedBy;
            
            item.ModifiedOn = ModifiedOn;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,int? CmCompanyID,int? CmMemberID,string CmMemberLevel,decimal? CmMemberRate,decimal? CmBalanceSum,decimal? CmBalanceCash,decimal? CmBalancePoint,DateTime? CmDate,int? CreatedBy,DateTime? CreatedOn,int? ModifiedBy,DateTime? ModifiedOn)
	    {
		    SysCompanyMember item = new SysCompanyMember();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.CmCompanyID = CmCompanyID;
				
			item.CmMemberID = CmMemberID;
				
			item.CmMemberLevel = CmMemberLevel;
				
			item.CmMemberRate = CmMemberRate;
				
			item.CmBalanceSum = CmBalanceSum;
				
			item.CmBalanceCash = CmBalanceCash;
				
			item.CmBalancePoint = CmBalancePoint;
				
			item.CmDate = CmDate;
				
			item.CreatedBy = CreatedBy;
				
			item.CreatedOn = CreatedOn;
				
			item.ModifiedBy = ModifiedBy;
				
			item.ModifiedOn = ModifiedOn;
				
	        item.Save(UserName);
	    }
    }
}
