using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Eleooo.DAL
{
    /// <summary>
    /// Controller class for Sys_Member_Config
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class SysMemberConfigController
    {
        // Preload our schema..
        SysMemberConfig thisSchemaLoad = new SysMemberConfig();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public SysMemberConfigCollection FetchAll()
        {
            SysMemberConfigCollection coll = new SysMemberConfigCollection();
            Query qry = new Query(SysMemberConfig.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public SysMemberConfigCollection FetchByID(object MemberId)
        {
            SysMemberConfigCollection coll = new SysMemberConfigCollection().Where("MemberId", MemberId).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public SysMemberConfigCollection FetchByQuery(Query qry)
        {
            SysMemberConfigCollection coll = new SysMemberConfigCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object MemberId)
        {
            return (SysMemberConfig.Delete(MemberId) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object MemberId)
        {
            return (SysMemberConfig.Destroy(MemberId) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int MemberId,DateTime? AreaModifyDate,int? AreaModifyCount,string MyFavCompany,string MyAddress,string MyRecItems,string MyRecAds,int? MsnPwdCount,DateTime? Area2ModifyDate,DateTime? PhoneModifyDate)
	    {
		    SysMemberConfig item = new SysMemberConfig();
		    
            item.MemberId = MemberId;
            
            item.AreaModifyDate = AreaModifyDate;
            
            item.AreaModifyCount = AreaModifyCount;
            
            item.MyFavCompany = MyFavCompany;
            
            item.MyAddress = MyAddress;
            
            item.MyRecItems = MyRecItems;
            
            item.MyRecAds = MyRecAds;
            
            item.MsnPwdCount = MsnPwdCount;
            
            item.Area2ModifyDate = Area2ModifyDate;
            
            item.PhoneModifyDate = PhoneModifyDate;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int MemberId,DateTime? AreaModifyDate,int? AreaModifyCount,string MyFavCompany,string MyAddress,string MyRecItems,string MyRecAds,int? MsnPwdCount,DateTime? Area2ModifyDate,DateTime? PhoneModifyDate)
	    {
		    SysMemberConfig item = new SysMemberConfig();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.MemberId = MemberId;
				
			item.AreaModifyDate = AreaModifyDate;
				
			item.AreaModifyCount = AreaModifyCount;
				
			item.MyFavCompany = MyFavCompany;
				
			item.MyAddress = MyAddress;
				
			item.MyRecItems = MyRecItems;
				
			item.MyRecAds = MyRecAds;
				
			item.MsnPwdCount = MsnPwdCount;
				
			item.Area2ModifyDate = Area2ModifyDate;
				
			item.PhoneModifyDate = PhoneModifyDate;
				
	        item.Save(UserName);
	    }
    }
}
