using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Eleooo.DAL
{
    /// <summary>
    /// Controller class for Sys_Reward
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class SysRewardController
    {
        // Preload our schema..
        SysReward thisSchemaLoad = new SysReward();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public SysRewardCollection FetchAll()
        {
            SysRewardCollection coll = new SysRewardCollection();
            Query qry = new Query(SysReward.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public SysRewardCollection FetchByID(object RewardID)
        {
            SysRewardCollection coll = new SysRewardCollection().Where("RewardID", RewardID).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public SysRewardCollection FetchByQuery(Query qry)
        {
            SysRewardCollection coll = new SysRewardCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object RewardID)
        {
            return (SysReward.Delete(RewardID) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object RewardID)
        {
            return (SysReward.Destroy(RewardID) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(DateTime? RewardDate,DateTime? RewardEndDate,decimal? RewardRate,int? RewardFlag,string RewardMemo)
	    {
		    SysReward item = new SysReward();
		    
            item.RewardDate = RewardDate;
            
            item.RewardEndDate = RewardEndDate;
            
            item.RewardRate = RewardRate;
            
            item.RewardFlag = RewardFlag;
            
            item.RewardMemo = RewardMemo;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int RewardID,DateTime? RewardDate,DateTime? RewardEndDate,decimal? RewardRate,int? RewardFlag,string RewardMemo)
	    {
		    SysReward item = new SysReward();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.RewardID = RewardID;
				
			item.RewardDate = RewardDate;
				
			item.RewardEndDate = RewardEndDate;
				
			item.RewardRate = RewardRate;
				
			item.RewardFlag = RewardFlag;
				
			item.RewardMemo = RewardMemo;
				
	        item.Save(UserName);
	    }
    }
}
