using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Eleooo.DAL
{
	/// <summary>
	/// Strongly-typed collection for the Payment class.
	/// </summary>
    [Serializable]
	public partial class PaymentCollection : ActiveList<Payment, PaymentCollection>
	{	   
		public PaymentCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>PaymentCollection</returns>
		public PaymentCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                Payment o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the Payment table.
	/// </summary>
	[Serializable]
	public partial class Payment : ActiveRecord<Payment>, IActiveRecord
	{
		#region .ctors and Default Settings
		static Payment( )
        {
            BaseSchema = DB.GetSchema("Payment");
        }
		public Payment()
		{
		  //InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public Payment(bool useDatabaseDefaults)
		{ 
            if(BaseSchema == null)
                BaseSchema = DB.GetSchema("Payment");
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public Payment(object keyID)
		{ 
            if(BaseSchema == null) 
                BaseSchema = DB.GetSchema("Payment");
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public Payment(string columnName, object columnValue)
		{ 
            if(BaseSchema == null) 
                BaseSchema = DB.GetSchema("Payment");
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
                {
                    BaseSchema = DB.GetSchema("Payment");
                }
				return BaseSchema;
			}
		}
		
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
		public int Id 
		{
			get { return GetColumnValue<int>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("PaymentCode")]
		[Bindable(true)]
		public string PaymentCode 
		{
			get { return GetColumnValue<string>(Columns.PaymentCode); }
			set { SetColumnValue(Columns.PaymentCode, value); }
		}
		  
		[XmlAttribute("PaymentDate")]
		[Bindable(true)]
		public DateTime PaymentDate 
		{
			get { return GetColumnValue<DateTime>(Columns.PaymentDate); }
			set { SetColumnValue(Columns.PaymentDate, value); }
		}
		  
		[XmlAttribute("PaymentMemberID")]
		[Bindable(true)]
		public int? PaymentMemberID 
		{
			get { return GetColumnValue<int?>(Columns.PaymentMemberID); }
			set { SetColumnValue(Columns.PaymentMemberID, value); }
		}
		  
		[XmlAttribute("PaymentCompanyID")]
		[Bindable(true)]
		public int? PaymentCompanyID 
		{
			get { return GetColumnValue<int?>(Columns.PaymentCompanyID); }
			set { SetColumnValue(Columns.PaymentCompanyID, value); }
		}
		  
		[XmlAttribute("PaymentEmail")]
		[Bindable(true)]
		public string PaymentEmail 
		{
			get { return GetColumnValue<string>(Columns.PaymentEmail); }
			set { SetColumnValue(Columns.PaymentEmail, value); }
		}
		  
		[XmlAttribute("PaymentSum")]
		[Bindable(true)]
		public decimal PaymentSum 
		{
			get { return GetColumnValue<decimal>(Columns.PaymentSum); }
			set { SetColumnValue(Columns.PaymentSum, value); }
		}
		  
		[XmlAttribute("PaymentMemo")]
		[Bindable(true)]
		public string PaymentMemo 
		{
			get { return GetColumnValue<string>(Columns.PaymentMemo); }
			set { SetColumnValue(Columns.PaymentMemo, value); }
		}
		  
		[XmlAttribute("PaymentStatus")]
		[Bindable(true)]
		public int PaymentStatus 
		{
			get { return GetColumnValue<int>(Columns.PaymentStatus); }
			set { SetColumnValue(Columns.PaymentStatus, value); }
		}
		  
		[XmlAttribute("PaymentType")]
		[Bindable(true)]
		public int? PaymentType 
		{
			get { return GetColumnValue<int?>(Columns.PaymentType); }
			set { SetColumnValue(Columns.PaymentType, value); }
		}
		  
		[XmlAttribute("PaymentOrderID")]
		[Bindable(true)]
		public int? PaymentOrderID 
		{
			get { return GetColumnValue<int?>(Columns.PaymentOrderID); }
			set { SetColumnValue(Columns.PaymentOrderID, value); }
		}
		  
		[XmlAttribute("CreatedBy")]
		[Bindable(true)]
		public int? CreatedBy 
		{
			get { return GetColumnValue<int?>(Columns.CreatedBy); }
			set { SetColumnValue(Columns.CreatedBy, value); }
		}
		  
		[XmlAttribute("CreatedOn")]
		[Bindable(true)]
		public DateTime? CreatedOn 
		{
			get { return GetColumnValue<DateTime?>(Columns.CreatedOn); }
			set { SetColumnValue(Columns.CreatedOn, value); }
		}
		  
		[XmlAttribute("ModifiedBy")]
		[Bindable(true)]
		public int? ModifiedBy 
		{
			get { return GetColumnValue<int?>(Columns.ModifiedBy); }
			set { SetColumnValue(Columns.ModifiedBy, value); }
		}
		  
		[XmlAttribute("ModifiedOn")]
		[Bindable(true)]
		public DateTime? ModifiedOn 
		{
			get { return GetColumnValue<DateTime?>(Columns.ModifiedOn); }
			set { SetColumnValue(Columns.ModifiedOn, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varPaymentCode,DateTime varPaymentDate,int? varPaymentMemberID,int? varPaymentCompanyID,string varPaymentEmail,decimal varPaymentSum,string varPaymentMemo,int varPaymentStatus,int? varPaymentType,int? varPaymentOrderID,int? varCreatedBy,DateTime? varCreatedOn,int? varModifiedBy,DateTime? varModifiedOn)
		{
			Payment item = new Payment();
			
			item.PaymentCode = varPaymentCode;
			
			item.PaymentDate = varPaymentDate;
			
			item.PaymentMemberID = varPaymentMemberID;
			
			item.PaymentCompanyID = varPaymentCompanyID;
			
			item.PaymentEmail = varPaymentEmail;
			
			item.PaymentSum = varPaymentSum;
			
			item.PaymentMemo = varPaymentMemo;
			
			item.PaymentStatus = varPaymentStatus;
			
			item.PaymentType = varPaymentType;
			
			item.PaymentOrderID = varPaymentOrderID;
			
			item.CreatedBy = varCreatedBy;
			
			item.CreatedOn = varCreatedOn;
			
			item.ModifiedBy = varModifiedBy;
			
			item.ModifiedOn = varModifiedOn;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varId,string varPaymentCode,DateTime varPaymentDate,int? varPaymentMemberID,int? varPaymentCompanyID,string varPaymentEmail,decimal varPaymentSum,string varPaymentMemo,int varPaymentStatus,int? varPaymentType,int? varPaymentOrderID,int? varCreatedBy,DateTime? varCreatedOn,int? varModifiedBy,DateTime? varModifiedOn)
		{
			Payment item = new Payment();
			
				item.Id = varId;
			
				item.PaymentCode = varPaymentCode;
			
				item.PaymentDate = varPaymentDate;
			
				item.PaymentMemberID = varPaymentMemberID;
			
				item.PaymentCompanyID = varPaymentCompanyID;
			
				item.PaymentEmail = varPaymentEmail;
			
				item.PaymentSum = varPaymentSum;
			
				item.PaymentMemo = varPaymentMemo;
			
				item.PaymentStatus = varPaymentStatus;
			
				item.PaymentType = varPaymentType;
			
				item.PaymentOrderID = varPaymentOrderID;
			
				item.CreatedBy = varCreatedBy;
			
				item.CreatedOn = varCreatedOn;
			
				item.ModifiedBy = varModifiedBy;
			
				item.ModifiedOn = varModifiedOn;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn PaymentCodeColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn PaymentDateColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn PaymentMemberIDColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn PaymentCompanyIDColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn PaymentEmailColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        public static TableSchema.TableColumn PaymentSumColumn
        {
            get { return Schema.Columns[6]; }
        }
        
        
        
        public static TableSchema.TableColumn PaymentMemoColumn
        {
            get { return Schema.Columns[7]; }
        }
        
        
        
        public static TableSchema.TableColumn PaymentStatusColumn
        {
            get { return Schema.Columns[8]; }
        }
        
        
        
        public static TableSchema.TableColumn PaymentTypeColumn
        {
            get { return Schema.Columns[9]; }
        }
        
        
        
        public static TableSchema.TableColumn PaymentOrderIDColumn
        {
            get { return Schema.Columns[10]; }
        }
        
        
        
        public static TableSchema.TableColumn CreatedByColumn
        {
            get { return Schema.Columns[11]; }
        }
        
        
        
        public static TableSchema.TableColumn CreatedOnColumn
        {
            get { return Schema.Columns[12]; }
        }
        
        
        
        public static TableSchema.TableColumn ModifiedByColumn
        {
            get { return Schema.Columns[13]; }
        }
        
        
        
        public static TableSchema.TableColumn ModifiedOnColumn
        {
            get { return Schema.Columns[14]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"ID";
			 public static string PaymentCode = @"PaymentCode";
			 public static string PaymentDate = @"PaymentDate";
			 public static string PaymentMemberID = @"PaymentMemberID";
			 public static string PaymentCompanyID = @"PaymentCompanyID";
			 public static string PaymentEmail = @"PaymentEmail";
			 public static string PaymentSum = @"PaymentSum";
			 public static string PaymentMemo = @"PaymentMemo";
			 public static string PaymentStatus = @"PaymentStatus";
			 public static string PaymentType = @"PaymentType";
			 public static string PaymentOrderID = @"PaymentOrderID";
			 public static string CreatedBy = @"CreatedBy";
			 public static string CreatedOn = @"CreatedOn";
			 public static string ModifiedBy = @"ModifiedBy";
			 public static string ModifiedOn = @"ModifiedOn";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
