using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Eleooo.DAL
{
	/// <summary>
	/// Strongly-typed collection for the SysMemberMove class.
	/// </summary>
    [Serializable]
	public partial class SysMemberMoveCollection : ActiveList<SysMemberMove, SysMemberMoveCollection>
	{	   
		public SysMemberMoveCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>SysMemberMoveCollection</returns>
		public SysMemberMoveCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                SysMemberMove o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the Sys_Member_Move table.
	/// </summary>
	[Serializable]
	public partial class SysMemberMove : ActiveRecord<SysMemberMove>, IActiveRecord
	{
		#region .ctors and Default Settings
		static SysMemberMove( )
        {
            BaseSchema = DB.GetSchema("Sys_Member_Move");
        }
		public SysMemberMove()
		{
		  //InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public SysMemberMove(bool useDatabaseDefaults)
		{ 
            if(BaseSchema == null)
                BaseSchema = DB.GetSchema("Sys_Member_Move");
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public SysMemberMove(object keyID)
		{ 
            if(BaseSchema == null) 
                BaseSchema = DB.GetSchema("Sys_Member_Move");
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public SysMemberMove(string columnName, object columnValue)
		{ 
            if(BaseSchema == null) 
                BaseSchema = DB.GetSchema("Sys_Member_Move");
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
                {
                    BaseSchema = DB.GetSchema("Sys_Member_Move");
                }
				return BaseSchema;
			}
		}
		
		#endregion
		
		#region Props
		  
		[XmlAttribute("MoveID")]
		[Bindable(true)]
		public int MoveID 
		{
			get { return GetColumnValue<int>(Columns.MoveID); }
			set { SetColumnValue(Columns.MoveID, value); }
		}
		  
		[XmlAttribute("MoverDate")]
		[Bindable(true)]
		public DateTime? MoverDate 
		{
			get { return GetColumnValue<DateTime?>(Columns.MoverDate); }
			set { SetColumnValue(Columns.MoverDate, value); }
		}
		  
		[XmlAttribute("MoverMemberIDOld")]
		[Bindable(true)]
		public int? MoverMemberIDOld 
		{
			get { return GetColumnValue<int?>(Columns.MoverMemberIDOld); }
			set { SetColumnValue(Columns.MoverMemberIDOld, value); }
		}
		  
		[XmlAttribute("MoverMemberIDNew")]
		[Bindable(true)]
		public int? MoverMemberIDNew 
		{
			get { return GetColumnValue<int?>(Columns.MoverMemberIDNew); }
			set { SetColumnValue(Columns.MoverMemberIDNew, value); }
		}
		  
		[XmlAttribute("MoverMemberIDPoint")]
		[Bindable(true)]
		public int? MoverMemberIDPoint 
		{
			get { return GetColumnValue<int?>(Columns.MoverMemberIDPoint); }
			set { SetColumnValue(Columns.MoverMemberIDPoint, value); }
		}
		  
		[XmlAttribute("CreatedBy")]
		[Bindable(true)]
		public int? CreatedBy 
		{
			get { return GetColumnValue<int?>(Columns.CreatedBy); }
			set { SetColumnValue(Columns.CreatedBy, value); }
		}
		  
		[XmlAttribute("CreatedOn")]
		[Bindable(true)]
		public DateTime? CreatedOn 
		{
			get { return GetColumnValue<DateTime?>(Columns.CreatedOn); }
			set { SetColumnValue(Columns.CreatedOn, value); }
		}
		  
		[XmlAttribute("ModifiedBy")]
		[Bindable(true)]
		public int? ModifiedBy 
		{
			get { return GetColumnValue<int?>(Columns.ModifiedBy); }
			set { SetColumnValue(Columns.ModifiedBy, value); }
		}
		  
		[XmlAttribute("ModifiedOn")]
		[Bindable(true)]
		public DateTime? ModifiedOn 
		{
			get { return GetColumnValue<DateTime?>(Columns.ModifiedOn); }
			set { SetColumnValue(Columns.ModifiedOn, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(DateTime? varMoverDate,int? varMoverMemberIDOld,int? varMoverMemberIDNew,int? varMoverMemberIDPoint,int? varCreatedBy,DateTime? varCreatedOn,int? varModifiedBy,DateTime? varModifiedOn)
		{
			SysMemberMove item = new SysMemberMove();
			
			item.MoverDate = varMoverDate;
			
			item.MoverMemberIDOld = varMoverMemberIDOld;
			
			item.MoverMemberIDNew = varMoverMemberIDNew;
			
			item.MoverMemberIDPoint = varMoverMemberIDPoint;
			
			item.CreatedBy = varCreatedBy;
			
			item.CreatedOn = varCreatedOn;
			
			item.ModifiedBy = varModifiedBy;
			
			item.ModifiedOn = varModifiedOn;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varMoveID,DateTime? varMoverDate,int? varMoverMemberIDOld,int? varMoverMemberIDNew,int? varMoverMemberIDPoint,int? varCreatedBy,DateTime? varCreatedOn,int? varModifiedBy,DateTime? varModifiedOn)
		{
			SysMemberMove item = new SysMemberMove();
			
				item.MoveID = varMoveID;
			
				item.MoverDate = varMoverDate;
			
				item.MoverMemberIDOld = varMoverMemberIDOld;
			
				item.MoverMemberIDNew = varMoverMemberIDNew;
			
				item.MoverMemberIDPoint = varMoverMemberIDPoint;
			
				item.CreatedBy = varCreatedBy;
			
				item.CreatedOn = varCreatedOn;
			
				item.ModifiedBy = varModifiedBy;
			
				item.ModifiedOn = varModifiedOn;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn MoveIDColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn MoverDateColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn MoverMemberIDOldColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn MoverMemberIDNewColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn MoverMemberIDPointColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn CreatedByColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        public static TableSchema.TableColumn CreatedOnColumn
        {
            get { return Schema.Columns[6]; }
        }
        
        
        
        public static TableSchema.TableColumn ModifiedByColumn
        {
            get { return Schema.Columns[7]; }
        }
        
        
        
        public static TableSchema.TableColumn ModifiedOnColumn
        {
            get { return Schema.Columns[8]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string MoveID = @"MoveID";
			 public static string MoverDate = @"MoverDate";
			 public static string MoverMemberIDOld = @"MoverMemberIDOld";
			 public static string MoverMemberIDNew = @"MoverMemberIDNew";
			 public static string MoverMemberIDPoint = @"MoverMemberIDPoint";
			 public static string CreatedBy = @"CreatedBy";
			 public static string CreatedOn = @"CreatedOn";
			 public static string ModifiedBy = @"ModifiedBy";
			 public static string ModifiedOn = @"ModifiedOn";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
