using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Eleooo.DAL
{
	/// <summary>
	/// Strongly-typed collection for the SysMemberCompany class.
	/// </summary>
    [Serializable]
	public partial class SysMemberCompanyCollection : ActiveList<SysMemberCompany, SysMemberCompanyCollection>
	{	   
		public SysMemberCompanyCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>SysMemberCompanyCollection</returns>
		public SysMemberCompanyCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                SysMemberCompany o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the Sys_Member_Company table.
	/// </summary>
	[Serializable]
	public partial class SysMemberCompany : ActiveRecord<SysMemberCompany>, IActiveRecord
	{
		#region .ctors and Default Settings
		static SysMemberCompany( )
        {
            BaseSchema = DB.GetSchema("Sys_Member_Company");
        }
		public SysMemberCompany()
		{
		  //InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public SysMemberCompany(bool useDatabaseDefaults)
		{ 
            if(BaseSchema == null)
                BaseSchema = DB.GetSchema("Sys_Member_Company");
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public SysMemberCompany(object keyID)
		{ 
            if(BaseSchema == null) 
                BaseSchema = DB.GetSchema("Sys_Member_Company");
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public SysMemberCompany(string columnName, object columnValue)
		{ 
            if(BaseSchema == null) 
                BaseSchema = DB.GetSchema("Sys_Member_Company");
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
                {
                    BaseSchema = DB.GetSchema("Sys_Member_Company");
                }
				return BaseSchema;
			}
		}
		
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
		public int Id 
		{
			get { return GetColumnValue<int>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("MemberCompanyMemberID")]
		[Bindable(true)]
		public int? MemberCompanyMemberID 
		{
			get { return GetColumnValue<int?>(Columns.MemberCompanyMemberID); }
			set { SetColumnValue(Columns.MemberCompanyMemberID, value); }
		}
		  
		[XmlAttribute("MemberCompanyCompanyID")]
		[Bindable(true)]
		public int? MemberCompanyCompanyID 
		{
			get { return GetColumnValue<int?>(Columns.MemberCompanyCompanyID); }
			set { SetColumnValue(Columns.MemberCompanyCompanyID, value); }
		}
		  
		[XmlAttribute("MemberCompanyDate")]
		[Bindable(true)]
		public DateTime? MemberCompanyDate 
		{
			get { return GetColumnValue<DateTime?>(Columns.MemberCompanyDate); }
			set { SetColumnValue(Columns.MemberCompanyDate, value); }
		}
		  
		[XmlAttribute("CreatedBy")]
		[Bindable(true)]
		public int? CreatedBy 
		{
			get { return GetColumnValue<int?>(Columns.CreatedBy); }
			set { SetColumnValue(Columns.CreatedBy, value); }
		}
		  
		[XmlAttribute("CreatedOn")]
		[Bindable(true)]
		public DateTime? CreatedOn 
		{
			get { return GetColumnValue<DateTime?>(Columns.CreatedOn); }
			set { SetColumnValue(Columns.CreatedOn, value); }
		}
		  
		[XmlAttribute("ModifiedBy")]
		[Bindable(true)]
		public int? ModifiedBy 
		{
			get { return GetColumnValue<int?>(Columns.ModifiedBy); }
			set { SetColumnValue(Columns.ModifiedBy, value); }
		}
		  
		[XmlAttribute("ModifiedOn")]
		[Bindable(true)]
		public DateTime? ModifiedOn 
		{
			get { return GetColumnValue<DateTime?>(Columns.ModifiedOn); }
			set { SetColumnValue(Columns.ModifiedOn, value); }
		}
		  
		[XmlAttribute("MemberGrade")]
		[Bindable(true)]
		public int? MemberGrade 
		{
			get { return GetColumnValue<int?>(Columns.MemberGrade); }
			set { SetColumnValue(Columns.MemberGrade, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(int? varMemberCompanyMemberID,int? varMemberCompanyCompanyID,DateTime? varMemberCompanyDate,int? varCreatedBy,DateTime? varCreatedOn,int? varModifiedBy,DateTime? varModifiedOn,int? varMemberGrade)
		{
			SysMemberCompany item = new SysMemberCompany();
			
			item.MemberCompanyMemberID = varMemberCompanyMemberID;
			
			item.MemberCompanyCompanyID = varMemberCompanyCompanyID;
			
			item.MemberCompanyDate = varMemberCompanyDate;
			
			item.CreatedBy = varCreatedBy;
			
			item.CreatedOn = varCreatedOn;
			
			item.ModifiedBy = varModifiedBy;
			
			item.ModifiedOn = varModifiedOn;
			
			item.MemberGrade = varMemberGrade;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varId,int? varMemberCompanyMemberID,int? varMemberCompanyCompanyID,DateTime? varMemberCompanyDate,int? varCreatedBy,DateTime? varCreatedOn,int? varModifiedBy,DateTime? varModifiedOn,int? varMemberGrade)
		{
			SysMemberCompany item = new SysMemberCompany();
			
				item.Id = varId;
			
				item.MemberCompanyMemberID = varMemberCompanyMemberID;
			
				item.MemberCompanyCompanyID = varMemberCompanyCompanyID;
			
				item.MemberCompanyDate = varMemberCompanyDate;
			
				item.CreatedBy = varCreatedBy;
			
				item.CreatedOn = varCreatedOn;
			
				item.ModifiedBy = varModifiedBy;
			
				item.ModifiedOn = varModifiedOn;
			
				item.MemberGrade = varMemberGrade;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn MemberCompanyMemberIDColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn MemberCompanyCompanyIDColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn MemberCompanyDateColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn CreatedByColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn CreatedOnColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        public static TableSchema.TableColumn ModifiedByColumn
        {
            get { return Schema.Columns[6]; }
        }
        
        
        
        public static TableSchema.TableColumn ModifiedOnColumn
        {
            get { return Schema.Columns[7]; }
        }
        
        
        
        public static TableSchema.TableColumn MemberGradeColumn
        {
            get { return Schema.Columns[8]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"ID";
			 public static string MemberCompanyMemberID = @"MemberCompany_MemberID";
			 public static string MemberCompanyCompanyID = @"MemberCompany_CompanyID";
			 public static string MemberCompanyDate = @"MemberCompany_Date";
			 public static string CreatedBy = @"CreatedBy";
			 public static string CreatedOn = @"CreatedOn";
			 public static string ModifiedBy = @"ModifiedBy";
			 public static string ModifiedOn = @"ModifiedOn";
			 public static string MemberGrade = @"MemberGrade";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
