using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Eleooo.DAL
{
    /// <summary>
    /// Controller class for Sys_Message
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class SysMessageController
    {
        // Preload our schema..
        SysMessage thisSchemaLoad = new SysMessage();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public SysMessageCollection FetchAll()
        {
            SysMessageCollection coll = new SysMessageCollection();
            Query qry = new Query(SysMessage.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public SysMessageCollection FetchByID(object Id)
        {
            SysMessageCollection coll = new SysMessageCollection().Where("ID", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public SysMessageCollection FetchByQuery(Query qry)
        {
            SysMessageCollection coll = new SysMessageCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (SysMessage.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (SysMessage.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int MessageType,int MessageSellerID,string MessageSubject,string MessageReply,int MessageSalerID,DateTime MessageDateSubject,decimal MessageDateReply,int? CreatedBy,DateTime? CreatedOn,int? ModifiedBy,DateTime? ModifiedOn)
	    {
		    SysMessage item = new SysMessage();
		    
            item.MessageType = MessageType;
            
            item.MessageSellerID = MessageSellerID;
            
            item.MessageSubject = MessageSubject;
            
            item.MessageReply = MessageReply;
            
            item.MessageSalerID = MessageSalerID;
            
            item.MessageDateSubject = MessageDateSubject;
            
            item.MessageDateReply = MessageDateReply;
            
            item.CreatedBy = CreatedBy;
            
            item.CreatedOn = CreatedOn;
            
            item.ModifiedBy = ModifiedBy;
            
            item.ModifiedOn = ModifiedOn;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,int MessageType,int MessageSellerID,string MessageSubject,string MessageReply,int MessageSalerID,DateTime MessageDateSubject,decimal MessageDateReply,int? CreatedBy,DateTime? CreatedOn,int? ModifiedBy,DateTime? ModifiedOn)
	    {
		    SysMessage item = new SysMessage();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.MessageType = MessageType;
				
			item.MessageSellerID = MessageSellerID;
				
			item.MessageSubject = MessageSubject;
				
			item.MessageReply = MessageReply;
				
			item.MessageSalerID = MessageSalerID;
				
			item.MessageDateSubject = MessageDateSubject;
				
			item.MessageDateReply = MessageDateReply;
				
			item.CreatedBy = CreatedBy;
				
			item.CreatedOn = CreatedOn;
				
			item.ModifiedBy = ModifiedBy;
				
			item.ModifiedOn = ModifiedOn;
				
	        item.Save(UserName);
	    }
    }
}
