using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Eleooo.DAL
{
    /// <summary>
    /// Controller class for Sys_Member_Move
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class SysMemberMoveController
    {
        // Preload our schema..
        SysMemberMove thisSchemaLoad = new SysMemberMove();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public SysMemberMoveCollection FetchAll()
        {
            SysMemberMoveCollection coll = new SysMemberMoveCollection();
            Query qry = new Query(SysMemberMove.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public SysMemberMoveCollection FetchByID(object MoveID)
        {
            SysMemberMoveCollection coll = new SysMemberMoveCollection().Where("MoveID", MoveID).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public SysMemberMoveCollection FetchByQuery(Query qry)
        {
            SysMemberMoveCollection coll = new SysMemberMoveCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object MoveID)
        {
            return (SysMemberMove.Delete(MoveID) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object MoveID)
        {
            return (SysMemberMove.Destroy(MoveID) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(DateTime? MoverDate,int? MoverMemberIDOld,int? MoverMemberIDNew,int? MoverMemberIDPoint,int? CreatedBy,DateTime? CreatedOn,int? ModifiedBy,DateTime? ModifiedOn)
	    {
		    SysMemberMove item = new SysMemberMove();
		    
            item.MoverDate = MoverDate;
            
            item.MoverMemberIDOld = MoverMemberIDOld;
            
            item.MoverMemberIDNew = MoverMemberIDNew;
            
            item.MoverMemberIDPoint = MoverMemberIDPoint;
            
            item.CreatedBy = CreatedBy;
            
            item.CreatedOn = CreatedOn;
            
            item.ModifiedBy = ModifiedBy;
            
            item.ModifiedOn = ModifiedOn;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int MoveID,DateTime? MoverDate,int? MoverMemberIDOld,int? MoverMemberIDNew,int? MoverMemberIDPoint,int? CreatedBy,DateTime? CreatedOn,int? ModifiedBy,DateTime? ModifiedOn)
	    {
		    SysMemberMove item = new SysMemberMove();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.MoveID = MoveID;
				
			item.MoverDate = MoverDate;
				
			item.MoverMemberIDOld = MoverMemberIDOld;
				
			item.MoverMemberIDNew = MoverMemberIDNew;
				
			item.MoverMemberIDPoint = MoverMemberIDPoint;
				
			item.CreatedBy = CreatedBy;
				
			item.CreatedOn = CreatedOn;
				
			item.ModifiedBy = ModifiedBy;
				
			item.ModifiedOn = ModifiedOn;
				
	        item.Save(UserName);
	    }
    }
}
