using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Eleooo.DAL
{
    /// <summary>
    /// Controller class for Sys_Member_Company
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class SysMemberCompanyController
    {
        // Preload our schema..
        SysMemberCompany thisSchemaLoad = new SysMemberCompany();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public SysMemberCompanyCollection FetchAll()
        {
            SysMemberCompanyCollection coll = new SysMemberCompanyCollection();
            Query qry = new Query(SysMemberCompany.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public SysMemberCompanyCollection FetchByID(object Id)
        {
            SysMemberCompanyCollection coll = new SysMemberCompanyCollection().Where("ID", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public SysMemberCompanyCollection FetchByQuery(Query qry)
        {
            SysMemberCompanyCollection coll = new SysMemberCompanyCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (SysMemberCompany.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (SysMemberCompany.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int? MemberCompanyMemberID,int? MemberCompanyCompanyID,DateTime? MemberCompanyDate,int? CreatedBy,DateTime? CreatedOn,int? ModifiedBy,DateTime? ModifiedOn,int? MemberGrade)
	    {
		    SysMemberCompany item = new SysMemberCompany();
		    
            item.MemberCompanyMemberID = MemberCompanyMemberID;
            
            item.MemberCompanyCompanyID = MemberCompanyCompanyID;
            
            item.MemberCompanyDate = MemberCompanyDate;
            
            item.CreatedBy = CreatedBy;
            
            item.CreatedOn = CreatedOn;
            
            item.ModifiedBy = ModifiedBy;
            
            item.ModifiedOn = ModifiedOn;
            
            item.MemberGrade = MemberGrade;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,int? MemberCompanyMemberID,int? MemberCompanyCompanyID,DateTime? MemberCompanyDate,int? CreatedBy,DateTime? CreatedOn,int? ModifiedBy,DateTime? ModifiedOn,int? MemberGrade)
	    {
		    SysMemberCompany item = new SysMemberCompany();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.MemberCompanyMemberID = MemberCompanyMemberID;
				
			item.MemberCompanyCompanyID = MemberCompanyCompanyID;
				
			item.MemberCompanyDate = MemberCompanyDate;
				
			item.CreatedBy = CreatedBy;
				
			item.CreatedOn = CreatedOn;
				
			item.ModifiedBy = ModifiedBy;
				
			item.ModifiedOn = ModifiedOn;
				
			item.MemberGrade = MemberGrade;
				
	        item.Save(UserName);
	    }
    }
}
