using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Eleooo.DAL
{
    /// <summary>
    /// Controller class for Sys_Member_Cash
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class SysMemberCashController
    {
        // Preload our schema..
        SysMemberCash thisSchemaLoad = new SysMemberCash();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public SysMemberCashCollection FetchAll()
        {
            SysMemberCashCollection coll = new SysMemberCashCollection();
            Query qry = new Query(SysMemberCash.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public SysMemberCashCollection FetchByID(object CashID)
        {
            SysMemberCashCollection coll = new SysMemberCashCollection().Where("CashID", CashID).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public SysMemberCashCollection FetchByQuery(Query qry)
        {
            SysMemberCashCollection coll = new SysMemberCashCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object CashID)
        {
            return (SysMemberCash.Delete(CashID) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object CashID)
        {
            return (SysMemberCash.Destroy(CashID) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(DateTime? CashDate,int? CashMemberID,int? CashCompanyID,int? CashOrderID,decimal? CashSum,decimal? CashRate,decimal? CashRateSale,decimal? CashPoint,string CashMemo,int? CreatedBy,DateTime? CreatedOn,int? ModifiedBy,DateTime? ModifiedOn)
	    {
		    SysMemberCash item = new SysMemberCash();
		    
            item.CashDate = CashDate;
            
            item.CashMemberID = CashMemberID;
            
            item.CashCompanyID = CashCompanyID;
            
            item.CashOrderID = CashOrderID;
            
            item.CashSum = CashSum;
            
            item.CashRate = CashRate;
            
            item.CashRateSale = CashRateSale;
            
            item.CashPoint = CashPoint;
            
            item.CashMemo = CashMemo;
            
            item.CreatedBy = CreatedBy;
            
            item.CreatedOn = CreatedOn;
            
            item.ModifiedBy = ModifiedBy;
            
            item.ModifiedOn = ModifiedOn;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int CashID,DateTime? CashDate,int? CashMemberID,int? CashCompanyID,int? CashOrderID,decimal? CashSum,decimal? CashRate,decimal? CashRateSale,decimal? CashPoint,string CashMemo,int? CreatedBy,DateTime? CreatedOn,int? ModifiedBy,DateTime? ModifiedOn)
	    {
		    SysMemberCash item = new SysMemberCash();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.CashID = CashID;
				
			item.CashDate = CashDate;
				
			item.CashMemberID = CashMemberID;
				
			item.CashCompanyID = CashCompanyID;
				
			item.CashOrderID = CashOrderID;
				
			item.CashSum = CashSum;
				
			item.CashRate = CashRate;
				
			item.CashRateSale = CashRateSale;
				
			item.CashPoint = CashPoint;
				
			item.CashMemo = CashMemo;
				
			item.CreatedBy = CreatedBy;
				
			item.CreatedOn = CreatedOn;
				
			item.ModifiedBy = ModifiedBy;
				
			item.ModifiedOn = ModifiedOn;
				
	        item.Save(UserName);
	    }
    }
}
