using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Eleooo.DAL
{
    /// <summary>
    /// Controller class for Sys_Support_Message
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class SysSupportMessageController
    {
        // Preload our schema..
        SysSupportMessage thisSchemaLoad = new SysSupportMessage();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public SysSupportMessageCollection FetchAll()
        {
            SysSupportMessageCollection coll = new SysSupportMessageCollection();
            Query qry = new Query(SysSupportMessage.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public SysSupportMessageCollection FetchByID(object SupportMsgId)
        {
            SysSupportMessageCollection coll = new SysSupportMessageCollection().Where("SupportMsg_ID", SupportMsgId).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public SysSupportMessageCollection FetchByQuery(Query qry)
        {
            SysSupportMessageCollection coll = new SysSupportMessageCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object SupportMsgId)
        {
            return (SysSupportMessage.Delete(SupportMsgId) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object SupportMsgId)
        {
            return (SysSupportMessage.Destroy(SupportMsgId) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int SupportMsgSid,int SupportMsgFid,int SupportMsgTid,string SupportMsgMemo,string SupportMsgPhoto,bool SupportMsgIsRead,bool SupportMsgIsAsk,DateTime SupportMsgDate,int? CreatedBy,DateTime? CreatedOn,int? ModifiedBy,DateTime? ModifiedOn)
	    {
		    SysSupportMessage item = new SysSupportMessage();
		    
            item.SupportMsgSid = SupportMsgSid;
            
            item.SupportMsgFid = SupportMsgFid;
            
            item.SupportMsgTid = SupportMsgTid;
            
            item.SupportMsgMemo = SupportMsgMemo;
            
            item.SupportMsgPhoto = SupportMsgPhoto;
            
            item.SupportMsgIsRead = SupportMsgIsRead;
            
            item.SupportMsgIsAsk = SupportMsgIsAsk;
            
            item.SupportMsgDate = SupportMsgDate;
            
            item.CreatedBy = CreatedBy;
            
            item.CreatedOn = CreatedOn;
            
            item.ModifiedBy = ModifiedBy;
            
            item.ModifiedOn = ModifiedOn;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int SupportMsgId,int SupportMsgSid,int SupportMsgFid,int SupportMsgTid,string SupportMsgMemo,string SupportMsgPhoto,bool SupportMsgIsRead,bool SupportMsgIsAsk,DateTime SupportMsgDate,int? CreatedBy,DateTime? CreatedOn,int? ModifiedBy,DateTime? ModifiedOn)
	    {
		    SysSupportMessage item = new SysSupportMessage();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.SupportMsgId = SupportMsgId;
				
			item.SupportMsgSid = SupportMsgSid;
				
			item.SupportMsgFid = SupportMsgFid;
				
			item.SupportMsgTid = SupportMsgTid;
				
			item.SupportMsgMemo = SupportMsgMemo;
				
			item.SupportMsgPhoto = SupportMsgPhoto;
				
			item.SupportMsgIsRead = SupportMsgIsRead;
				
			item.SupportMsgIsAsk = SupportMsgIsAsk;
				
			item.SupportMsgDate = SupportMsgDate;
				
			item.CreatedBy = CreatedBy;
				
			item.CreatedOn = CreatedOn;
				
			item.ModifiedBy = ModifiedBy;
				
			item.ModifiedOn = ModifiedOn;
				
	        item.Save(UserName);
	    }
    }
}
