using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Eleooo.DAL
{
    /// <summary>
    /// Controller class for Sys_Takeaway_Directory
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class SysTakeawayDirectoryController
    {
        // Preload our schema..
        SysTakeawayDirectory thisSchemaLoad = new SysTakeawayDirectory();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public SysTakeawayDirectoryCollection FetchAll()
        {
            SysTakeawayDirectoryCollection coll = new SysTakeawayDirectoryCollection();
            Query qry = new Query(SysTakeawayDirectory.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public SysTakeawayDirectoryCollection FetchByID(object Id)
        {
            SysTakeawayDirectoryCollection coll = new SysTakeawayDirectoryCollection().Where("ID", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public SysTakeawayDirectoryCollection FetchByQuery(Query qry)
        {
            SysTakeawayDirectoryCollection coll = new SysTakeawayDirectoryCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (SysTakeawayDirectory.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (SysTakeawayDirectory.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string DirName,int? CompanyID)
	    {
		    SysTakeawayDirectory item = new SysTakeawayDirectory();
		    
            item.DirName = DirName;
            
            item.CompanyID = CompanyID;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,string DirName,int? CompanyID)
	    {
		    SysTakeawayDirectory item = new SysTakeawayDirectory();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.DirName = DirName;
				
			item.CompanyID = CompanyID;
				
	        item.Save(UserName);
	    }
    }
}
